googlefonts/glyphsLib

Lib/glyphs2ufo/__main__.py
setup.py

This adds a command line script `glyphs2ufo`.

Command line script

---

Lib/glyphs2ufo/casting.py
Lib/glyphs2ufo/glyphslib.py
Lib/glyphs2ufo/interpolation.py
Lib/glyphs2ufo/torf.py
Lib/glyphs2ufo/torf_test.py

Export flag is part of https://github.com/googlei18n/fontmake/issues/20, but this addresses some other things as well.

Info storage

---

Lib/glyphs2ufo/interpolation.py
Lib/glyphs2ufo/torf.py

Part of https://github.com/googlei18n/fontmake/issues/13

UFO3 kerning names and conflict removal

---

Lib/glyphs2ufo/interpolation.py

[interpolation] Designspace gen to separate func

---

Lib/glyphs2ufo/parser.py

[parser] Match linebreaks in quoted text

---

Lib/glyphs2ufo/glyphslib.py
Lib/glyphs2ufo/interpolation.py

Should fix https://github.com/googlei18n/fontmake/issues/60

Designspace document naming

---

Lib/glyphs2ufo/builder.py

A couple more custom parameter keys need to be changed so that they'll
be processed as OpenType table entries.

Change more OpenType custom param keys

---

Lib/glyphs2ufo/builder.py
Lib/glyphs2ufo/builder_test.py
Lib/glyphs2ufo/interpolation.py

We decided we want this after all.
cc @behdad

Put width in style name instead of family name

---

Lib/glyphs2ufo/builder.py
Lib/glyphs2ufo/interpolation.py

Propagate anchors from components

---

Lib/glyphsLib/builder.py
Lib/glyphsLib/casting.py

For now, this only adds production names which are present in the
Glyphs source.
Part of https://github.com/googlei18n/glyphsLib/issues/12

Add production names to glif libs

---

Lib/glyphsLib/builder.py
Lib/glyphsLib/casting.py
Lib/glyphsLib/interpolation.py

Handle three interpolation axes

---

Lib/glyphsLib/__init__.py
Lib/glyphsLib/__main__.py
Lib/glyphsLib/builder.py
Lib/glyphsLib/builder_test.py
Lib/glyphsLib/casting.py
Lib/glyphsLib/interpolation.py

Adds a couple more fields to UFO output, and uses a new heuristic to determine when fonts are italic (I'm not sure that anyone was using the old `italic` argument besides fontmake anyways).

Metadata fixes

---

Lib/glyphsLib/builder.py

(Turns out this *is* necessary, I just hadn't done enough testing)

Normalize custom parameter names

---

Lib/glyphsLib/builder.py
Lib/glyphsLib/builder_test.py

Matches Glyphs for kerning resolution.
Part of https://github.com/googlei18n/glyphsLib/issues/24, https://github.com/googlei18n/fontmake/issues/83

Kerning resolution

---

Lib/glyphsLib/__init__.py
Lib/glyphsLib/anchors.py
Lib/glyphsLib/builder.py
Lib/glyphsLib/builder_test.py
Lib/glyphsLib/casting.py
Lib/glyphsLib/casting_test.py
Lib/glyphsLib/interpolation.py
Lib/glyphsLib/parser.py

Fix Python 3 support

---

Lib/glyphsLib/builder.py
Lib/glyphsLib/builder_test.py
Lib/glyphsLib/casting.py

Enough to close https://github.com/googlei18n/glyphsLib/issues/64?

Check version

---

Lib/glyphsLib/builder.py

Follow up to last version-checking PR

Check for specific Glyphs version number

---

Lib/glyphsLib/__init__.py

see: https://github.com/googlei18n/fontmake/pull/122#issuecomment-237407590

glyphsLib.load_to_ufos: accept either file object or filesystem path

---

Lib/glyphsLib/builder.py
Lib/glyphsLib/builder_test.py
Lib/glyphsLib/casting.py

This is in order to _keep_ the original starting point's position.
https://github.com/googlei18n/fontmake/issues/142

[builder] make last node the first for closed contours

---

Lib/glyphsLib/builder.py
Lib/glyphsLib/interpolation.py
Lib/glyphsLib/util.py

Related issues:
https://github.com/googlei18n/fontmake/issues/211
https://github.com/googlei18n/fontmake/issues/144
/cc @jamesgk @brawer @robmck-ms

don't write unused dimension elements in designspace file

---

Lib/glyphsLib/builder.py
tests/builder_test.py

Resolves https://github.com/googlei18n/glyphsLib/issues/12

Use GlyphData for default production names

---

Lib/glyphsLib/builder.py
Lib/glyphsLib/glyphdata.py
tests/builder_test.py
tests/glyphdata_test.py

Resolves https://github.com/googlei18n/glyphsLib/issues/85

Generate GlyphClassDef statements in auto-generated table GDEF

---

MetaTools/generate_glyphdata.py

This simply makes the `generate_glyphdata` also work under Python 3.
The `glyphdata_generated` output does not change (still contains the same issue as #103).

[generate_glyphdata] make script compatible with Python 3

---

Lib/glyphsLib/builder.py
tests/builder_test.py

Fixes googlei18n/fontmake#246
/cc @robmck-ms

[builder] add support for 'glyphOrder' custom parameter

---

Lib/glyphsLib/casting.py
tests/casting_test.py

Fixes https://github.com/googlei18n/glyphsLib/issues/114

don't enforce int or float when reading custom parameters

---

Lib/glyphsLib/interpolation.py
tests/data/DesignspaceTestFamilyName.designspace
tests/interpolation_test.py

Fixes https://github.com/googlei18n/glyphsLib/issues/124.
See also https://github.com/googlei18n/fontmake/issues/257.

Support instances with custom family names

---

tests/data/DesignspaceTestInstanceOrder.designspace
tests/interpolation_test.py

https://github.com/googlei18n/glyphsLib/issues/113
https://github.com/googlei18n/fontmake/issues/188

Add test case for ordering designspace instances

---

Lib/glyphsLib/builder.py
tests/builder_test.py

Also optimizes the testcase structure by creating Font in setUp function.
#131

Add test case for underlineposition/thickness and set default values

---

Lib/glyphsLib/builder.py
Lib/glyphsLib/casting.py
tests/builder_test.py
tests/casting_test.py

handle empty or missing "date"

---

Lib/glyphsLib/builder.py
Lib/glyphsLib/util.py
setup.py
tests/builder_test.py
tox.ini

This is the first step of solving issue https://github.com/googlei18n/fontmake/issues/275 , following Cosimo's advice.
Keep the Filters in ufo.lib['com.github.googlei18n.ufo2ft.filters'] and let ufo2ft handle it.

add ufo2ft filters key in ufo.lib

---

Lib/glyphsLib/interpolation.py
tests/data/DesignspaceTestBasic.designspace
tests/data/DesignspaceTestFamilyName.designspace
tests/data/DesignspaceTestInactive.designspace
tests/data/DesignspaceTestInstanceOrder.designspace

https://github.com/googlei18n/fontmake/issues/167

Write axis label names into designspace documents

---

Lib/glyphsLib/interpolation.py
tests/interpolation_test.py

Fixes https://github.com/googlei18n/glyphsLib/issues/167.

Support postscriptFontName attribute

---

Lib/glyphsLib/interpolation.py

Fixes https://github.com/googlei18n/glyphsLib/issues/169

[interpolation] use 0 as default value for custom axis

---

Lib/glyphsLib/interpolation.py

In MutatorMath, one of the masters is used as the base for copying
default font information, and glyphsLib tries to use the "Regular"
master for this.
Before this change, the logic for finding the "regular" master was
interleaved with writing out the masters into the output designspace
file for MutatorMath. After this change, the logic is in a separate
function.
No change in functionality, just refactoring.

Refactor how glyphsLib finds the "Regular" master

---

Lib/glyphsLib/interpolation.py
tests/data/DesignspaceTestTwoAxes.designspace
tests/interpolation_test.py

Fixes https://github.com/googlei18n/glyphsLib/issues/170.

Take default axis values from "regular" interpolation master

---

Lib/glyphsLib/builder.py
Lib/glyphsLib/interpolation.py
tests/interpolation_test.py

Fixes https://github.com/googlei18n/glyphsLib/issues/176.

Support “Variation font origin” parameter

---

Lib/glyphsLib/builder.py
tests/builder_test.py

get Variation Font Origin from font-wide custom parameters

---

Lib/glyphsLib/builder.py
Lib/glyphsLib/interpolation.py
tests/builder_test.py
tests/data/DesignspaceTestTwoAxes.designspace
tests/interpolation_test.py

Fixes https://github.com/googlei18n/fontmake/issues/314 and https://github.com/googlei18n/fontmake/issues/337
See commit messages for info.

fix issues when providing custom family_name

---

Lib/glyphsLib/classes.py
tests/classes_test.py

Like in GlyphsApp, glyph.layers is ordered in the font.masters order, and glyph.layers.values() in the file glyph layer order.

Use LayersIterator

---

tests/writer_test.py

Fix incorrect test inputs

---

Lib/glyphsLib/builder/custom_params.py
Lib/glyphsLib/builder/filters.py
tests/builder_test.py

Fixes https://github.com/googlei18n/glyphsLib/issues/214

Export PreFilter custom parameter with pre=True

---

Lib/glyphsLib/__init__.py
Lib/glyphsLib/builder/features.py
Lib/glyphsLib/builder/glyph.py

Add missing import for glyphdata

---

Lib/glyphsLib/builder/custom_params.py
tests/builder_test.py

Fixes https://github.com/googlei18n/glyphsLib/issues/268

[custom_params] cast xHeight value to int

---

Lib/glyphsLib/classes.py
Lib/glyphsLib/parser.py
Lib/glyphsLib/types.py
Lib/glyphsLib/writer.py
tests/classes_test.py
tests/writer_test.py

This add a test for #286 and integrates pending changes from #277

Test node user data

---

Lib/glyphsLib/builder/builders.py
tests/builder_test.py

so that messages are emitted not from generic 'builders' module but from either UFOBuilder or GlyphsBuilder class, which is more specific.
Also, use CapturingLogHandler in builder_test.py::SkipDanglingAndNamelessLayers

[builders] add logger property to builder classes

---

Lib/glyphsLib/classes.py
tests/classes_test.py

Fixes https://github.com/googlei18n/glyphsLib/issues/323.

Generate the name of a master using family, width, weight, custom order

---

Lib/glyphsLib/parser.py
Lib/glyphsLib/writer.py
tests/parser_test.py
tests/writer_test.py

Writer: string that looks like float needs quotes

---

Lib/glyphsLib/builder/instances.py
Lib/glyphsLib/builder/sources.py
Lib/glyphsLib/interpolation.py
tests/builder/instances_test.py

allow to apply_instance_data to selected instances

---

Lib/glyphsLib/builder/axes.py
Lib/glyphsLib/builder/custom_params.py
Lib/glyphsLib/builder/masters.py
Lib/glyphsLib/builder/sources.py
tests/builder/axes_test.py

Fix #280 and #158
This uses & replaces the work started in #306

Handle custom axes

---

Lib/glyphsLib/builder/axes.py
tests/data/DesignspaceGenTestItalic.designspace
tests/data/DesignspaceGenTestRegular.designspace
tests/data/DesignspaceTestBasic.designspace
tests/data/DesignspaceTestFamilyName.designspace
tests/data/DesignspaceTestFileName.designspace
tests/data/DesignspaceTestInactive.designspace
tests/data/DesignspaceTestInstanceOrder.designspace
tests/data/DesignspaceTestTwoAxes.designspace

Omit default labelnames

---

Lib/glyphsLib/parser.py
tests/parser_test.py

As encountered in a Glyphs 2.5 file.

Handle hex binary data

---

.gitignore
Lib/glyphsLib/__init__.py
setup.py

This simplifies the release process greatly.

Switch from bump_version to setuptools_scm

---

Lib/glyphsLib/builder/custom_params.py
tests/builder/custom_params_test.py
tests/builder/fontinfo_test.py

Fix openTypeOS2Selection handling

---

Lib/glyphsLib/glyphdata.py
tests/glyphdata_test.py

Properly handle categorization of glyph variants

---

Lib/glyphsLib/glyphdata.py

glyphdata.py: Fix minor typo

---

Lib/glyphsLib/cli.py
setup.py
tests/main_test.py

Make UFO normalization optional

---

Lib/glyphsLib/builder/features.py
tests/builder/features_test.py

See https://github.com/googlei18n/glyphsLib/issues/422.

UFO roundtripping: keep groups at top

---

tests/builder/features_test.py

Don't want to throw the code away.
Any suggestions for more tests?

Add test for preserving a GDEF table

---

Lib/glyphsLib/builder/masters.py
tests/builder/builder_test.py

Fixes https://github.com/googlei18n/glyphsLib/issues/400.

Make sure fontMasterID lib keys in UFOs are unique

---

Lib/glyphsLib/classes.py
Lib/glyphsLib/parser.py
tests/parser_test.py
tests/writer_test.py

Fixes https://github.com/googlei18n/fontmake/issues/445

Fix parsing backslash escaped glyph names in features

---

Lib/glyphsLib/builder/features.py

Following the discussion at https://github.com/googlei18n/glyphsLib/issues/427.

WIP: GDEF generation cleanup

---

Lib/glyphsLib/classes.py
tests/classes_test.py

https://github.com/googlei18n/glyphsLib/issues/380

fix "Regular Italic" redundant master name

---

Lib/glyphsLib/classes.py
Lib/glyphsLib/types.py

* Simplify Point `__init__` to speed up instantiation
* Use `__slots__` to shave off a few ns.
Supersedes https://github.com/googlei18n/glyphsLib/pull/450.

Minor performance improvement for Point

---

setup.cfg

Do not run pytest verbosely

---

Lib/glyphsLib/classes.py
tests/classes_test.py

Fixes https://github.com/googlei18n/fontmake/issues/479 ?

don't append duplicated 'Italic' to master.name with italicAngle

---

Lib/glyphsLib/glyphdata.py
tests/glyphdata_test.py

Partly cover https://github.com/googlei18n/glyphsLib/issues/507.

glyphdata: Try harder to determine (sub)category

---

Lib/glyphsLib/builder/instances.py
Lib/glyphsLib/interpolation.py

I want to use it in fontmake to do in-memory manipulation.

Factor out the application of Glyphs instance data

---

Lib/glyphsLib/builder/builders.py
Lib/glyphsLib/builder/glyph.py
Lib/glyphsLib/classes.py
Lib/glyphsLib/interpolation.py
Lib/glyphsLib/types.py
Lib/glyphsLib/util.py
tests/writer_test.py

Strip `# type: ...` comments, etc.

Fix flake8 complaints

---

Lib/glyphsLib/builder/custom_params.py
Lib/glyphsLib/builder/features.py
tests/builder/custom_params_test.py

Fixes #529
Supersedes #534
/cc @punchcutter @marekjez86

Add support for 'Replace Prefix' custom parameter

---

Lib/glyphsLib/builder/constants.py
Lib/glyphsLib/builder/instances.py
Lib/glyphsLib/builder/masters.py
Lib/glyphsLib/builder/sources.py
Lib/glyphsLib/cli.py
tests/builder/custom_params_test.py
tests/data/UFOFilenameTest.glyphs

Closes https://github.com/googlefonts/glyphsLib/issues/319.

Save UFO filenames for masters and instances in custom parameter

---

Lib/glyphsLib/builder/instances.py
tests/builder/instances_test.py

Closes https://github.com/googlefonts/glyphsLib/issues/555.

apply_instance_data: only apply OS/2 wght/wdth class when corresponding axis exists

---

Lib/glyphsLib/builder/builders.py
tests/builder/designspace_gen_test.py

Fixes https://github.com/googlefonts/glyphsLib/issues/578
This is the easier way.
I'll come up with a test after lunch.

update autogenerated GDEF table after applying bracket glyphs

---

Lib/glyphsLib/builder/blue_values.py
Lib/glyphsLib/builder/custom_params.py
Lib/glyphsLib/builder/paths.py
Lib/glyphsLib/builder/user_data.py
Lib/glyphsLib/classes.py
tests/builder/builder_test.py
tests/builder/lib_and_user_data_test.py

Closes https://github.com/googlefonts/glyphsLib/issues/584.

Cut down on noise

---

Lib/glyphsLib/builder/paths.py
Lib/glyphsLib/classes.py
tests/data/PenTest.glyphs
tests/pen_test.py

In preparation for decomposition of non-default layer components decomposition, implement a pen and draw methods.
Closes #601.

Add pen and draw

---

Lib/glyphsLib/builder/builders.py
Lib/glyphsLib/builder/custom_params.py
Lib/glyphsLib/builder/glyph.py
Lib/glyphsLib/builder/masters.py
Lib/glyphsLib/classes.py
tests/builder/to_glyphs_test.py

This pr will solve #597 
My implementation is based on Cosimo's https://github.com/googlefonts/glyphsLib/issues/557#issuecomment-667074856.

Improve vertical typesetting

---

.github/workflows/publish.yml
.github/workflows/test.yml
tox.ini

Literally the same workflow files as ufo2ft. You will need to set `PYPI_USERNAME` and `PYPI_PASSWORD` in repository secrets.

Run tests/publish with GitHub actions, fixes #645

---

Lib/glyphsLib/builder/builders.py
Lib/glyphsLib/builder/features.py
Lib/glyphsLib/builder/masters.py

... otherwise, the 'Replace Feature' custom parameter will not work for masters, as it finds the features.fea text empty.
Similar to https://github.com/googlefonts/glyphsLib/pull/571 but rebased off latest master.

apply master custom params _after_ writing master UFO features

---

Lib/glyphsLib/builder/builders.py
Lib/glyphsLib/builder/groups.py
Lib/glyphsLib/builder/kerning.py
tests/builder/builder_test.py
tests/data/BracketTestFontKerning.glyphs

Bracket glyphs inherit their parents' kerning.

Roundtrip bracket glyph kerning

---

tests/glyphdata_test.py

https://github.com/schriftgestalt/GlyphsInfo/commit/0fe81a08dee6e7614c0f196e6668a9aafaad0d3e

Update GlyphData.xml to commit 0fe81a0

---

Lib/glyphsLib/builder/font.py
Lib/glyphsLib/builder/glyph.py
Lib/glyphsLib/builder/masters.py
tests/builder/to_glyphs_test.py

Fixes https://github.com/googlefonts/glyphsLib/issues/557#issuecomment-768020307

check that vert{Width,Origin} are not None, can be 0

---

.github/workflows/regression.yml

Followup from https://github.com/googlefonts/glyphsLib/pull/697.

Use main as the comparison point for regression testing

---

Lib/glyphsLib/builder/builders.py
tests/builder/designspace_gen_test.py

Fix brace layers in minimal build

---

Lib/glyphsLib/builder/features.py

see issue googlefonts/glyphsLib#694

Handle features.fea code where a mark class is used as a glyph class

---

requirements-dev.txt
requirements.txt
setup.cfg
tests/data/DesignspaceGenTestItalic.designspace
tests/data/DesignspaceGenTestRegular.designspace
tests/data/DesignspaceTestBasic.designspace
tests/data/DesignspaceTestFamilyName.designspace
tests/data/DesignspaceTestFileName.designspace
tests/data/DesignspaceTestInactive.designspace
tests/data/DesignspaceTestInstanceOrder.designspace
tests/data/DesignspaceTestTwoAxes.designspace

This fixes #787 by applying new data back to the expected test results.  Please review the results before merge.

test: update DesignSpace test data from newer version of fontTools

---

README.builder.md

`glyphsLib.builder` is hard to follow. This overview makes it easier.

Add sketch of glyphsLib.builder

---

Lib/glyphsLib/builder/custom_params.py
tests/builder/instances_test.py
tests/data/RenameGlyphsTest.glyphs

- Rename Glyphs custom parameter implementation
- Add tests for rename glyphs

Implement Rename Glyphs custom parameter

---

Lib/glyphsLib/classes.py
tests/data/GlyphsFileFormatv2.glyphs
tests/writer_test.py

Keep keys sorted alphabetically during serialization

---

Lib/glyphsLib/builder/hints.py
Lib/glyphsLib/classes.py
Lib/glyphsLib/types.py
tests/data/GlyphsFileFormatv2.diff
tests/data/GlyphsFileFormatv3.diff
tests/data/GlyphsFileFormatv3.glyphs
tests/main_test.py
tests/writer_test.py

Update the official reference for format 3

---

Lib/glyphsLib/builder/components.py
tests/builder/builder_test.py

Glyphs handles components for color layers in a special way. If the component glyph has color layers of its own, the component use the first color layer with the same color index, otherwise it fallback to the default layer. We try to do that here as well.
Fixes https://github.com/googlefonts/glyphsLib/issues/866

Fix handling of COLRv0 layers

---

Lib/glyphsLib/builder/smart_components.py
Lib/glyphsLib/types.py
tests/smart_components_test.py

Fixes https://github.com/googlefonts/glyphsLib/issues/882

[smart_components] Fix flipped component path direction

---

Lib/glyphsLib/classes.py
tests/builder/instances_test.py
tests/data/InstanceFamilyName-G3.glyphs

As discussed in #881, this PR adds more tests.

Add tests for name accessors in GSInstance

---

Lib/glyphsLib/builder/constants.py
Lib/glyphsLib/builder/custom_params.py

This is to incorporate Georg's property list in #881.

Register all known properties in format 3

---

Lib/glyphsLib/classes.py

Fix glyphs3 brace coordinates being returned as non-int

---

Lib/glyphsLib/builder/tokens.py
tests/tokens_test.py

should fix the `AttributeError: 'GSLayer' object has no attribute '.5'` part of #914

fix float factors in tokens

---

Lib/glyphsLib/parser.py
tests/data/GlyphsUnitTestSans3.glyphspackage/UIState.plist
tests/glyphs3_test.py

It contains DisplayStrings, and possibly other data. The DisplayStrings key starts with a lowercase, which is unfortunate, so I added a hack for it.

Load UIState.plist file from .glyphspackage

---

Lib/glyphsLib/classes.py
tests/classes_test.py

Stop infinite loop in .segments with quadratic curves

---

Lib/glyphsLib/builder/tokens.py
tests/data/TokenTest.glyphs

Skip unexported glyphs when parsing tokens

---

Lib/glyphsLib/classes.py
tests/classes_test.py

This is a much cleaner `GSPath.segments` implementation, with no infinite loop.

.segments again

---

Lib/glyphsLib/builder/transformations/intermediate_layers.py

See https://github.com/googlefonts/glyphsLib/pull/971#issuecomment-1919192625

Copy intermediate layer location directly from parent

---

Lib/glyphsLib/classes.py
tests/classes_test.py

the first commit adds a test to reproduce https://github.com/googlefonts/glyphsLib/issues/1013
will follow up with the actual fix

Fix iterating over layers of 'orphan' GSGlyph

---

tests/data/RTL_kerning_v3.glyphs
tests/glyphs3_test.py

to reproduce #1039
Will be fixed by #1041

modify `test_glyphs3_rtl_kerning` to add a mix of LTR and RTL kerns

---

Lib/glyphsLib/builder/paths.py

Fix indentation (point identifiers Glyphs3)

---

Lib/glyphsLib/builder/constants.py
Lib/glyphsLib/builder/glyph.py

Just fixes flake8 lint error https://github.com/googlefonts/glyphsLib/pull/1061#issuecomment-2618782475

Fix flake8 errors

---

Lib/glyphsLib/builder/bracket_layers.py
Lib/glyphsLib/builder/transformations/__init__.py
Lib/glyphsLib/builder/transformations/align_alternate_layers.py
tests/builder/transformations/align_alternate_layers_test.py
tests/builder/transformations/propagate_anchors_test.py
tests/data/AlignAlternateLayers-g2.glyphs
tests/data/AlignAlternateLayers-g3.glyphs

... to be performed before `propagate_all_anchors`, so that anchors are correctly propagated to composite glyphs referencing components with alternate layers. 
Fixes #1090

[bracket_layers] add align_alternate_layers preflight transformation
