googlefonts/glyphsLib

- Lib/glyphs2ufo/parser.py
If there are `$`s in Glyphs tabs, they are stored as non-quoted values in .glyphs file, for example:  [dollar.glyphs](https://gist.github.com/mashabow/31b45622d8ce5d2f9c7c "dollar.glyphs"). But glyphs2ufo's parser fails to parse such .glyphs file.
This PR fixes it.
> Allow dollar signs when parsing non-quoted values

- Lib/glyphs2ufo/torf.py
- Also support more weights, e.g. SemiLight, DemiLight, DemiBold,
Regular, empty string (to handle cases where 'Italic' was removed
leaving no weight-- defaults to Regular in this case).
> Warn about unrecognized weights in get_weight_code.

- Lib/glyphs2ufo/casting.py
- Lib/glyphs2ufo/interpolation.py
- Lib/glyphs2ufo/torf.py
This allows more custom parameters to be loaded into instance UFOs, using the same code that loads them for masters.
Part of https://github.com/googlei18n/fontmake/issues/20 in that some of these custom parameters are used for filtering glyph output.
> Improve instance custom param handling

- Lib/glyphs2ufo/glyphslib.py
- Lib/glyphs2ufo/interpolation.py
Related to https://github.com/googlei18n/fontmake/issues/62. Names were not being applied to output properly before, and instances were getting mixed up.
> Use instance family names

- Lib/glyphs2ufo/builder.py
- Lib/glyphs2ufo/builder_test.py
- Lib/glyphs2ufo/interpolation.py
This is instead of the weight/widthClass fields, which we used before
simply for convenience but are not used by Glyphs itself. We do still
want to split the width and weight into two separate words for the
style name, so this pulls out a shared style parsing method.
> [interpolation] Use name field from instance data

- Lib/glyphs2ufo/builder.py
- Lib/glyphs2ufo/interpolation.py
glyphs2ufo should not require defcon or mutatorMath if a user just wants to parse a .glyphs file using `glyphs2ufo.glyphslib.load` or `loads` functions, but does not want to also dump it to ufo.
> don't import defcon/mutatorMath in global scope

- Lib/glyphsLib/builder.py
- Lib/glyphsLib/interpolation.py
For reason described in comments. When a UFO is overwritten, old glyphs are never removed. So we have to do this manually.
Should fix any issue for which removing old output was the solution. cc @marekjez86
> Remove old instance_ufo output before writing

- Lib/glyphsLib/casting.py
- Lib/glyphsLib/parser.py
This changes the parsing code to handle octal/unicode escapes as well
as quotes.  This means that unicode values are returned from the parser,
and may be passed to the writer.
The casting code no longer normalizes curly quotes, they are maintained in
the data.  If they need to normalized clients will need to do that conversion.
This allows for better round-tripping of the original glyphs data.
Note that it is not possible to fully round-trip the glyphs source.  In
particular leading spaces are not preserved.  Quoting of strings is also
not fully preserved, instead the determination of whether strings need to
be quoted is done based on the contents of the string.  Glyphs seems to
quote and indent based on the position of the element in the hierarchy and
not on the content.  This does not …
> Add code for writing typed/untyped data to glyphs files.

- Lib/glyphsLib/interpolation.py
This tries to use the most regular master (either the master with
style Regular, or a style common between masters) before falling back
on just using the first master.
Also fixes a bug in which the first master's style was always included
in the designspace path.
Part of https://github.com/googlei18n/fontmake/issues/73
> Try to source metadata from regular master

- Lib/glyphsLib/casting.py
Glyphs seems to accept floats for instances' interpolation values, so they should be `num`, like #21.
> Change interpolation{Weight,Width,Custom} from int to num

- Lib/glyphsLib/builder.py
For one thing, these are strictly conflicts and not duplicates. Also,
identify the master as there can be more than one conflict for the
same pair in a single Glyphs source (but not in a single master).
> Give more descriptive warnings about kerning

- Lib/glyphsLib/__init__.py
- Lib/glyphsLib/builder.py
- Lib/glyphsLib/interpolation.py
This allows one to only build certain instances found in a Glyphs source, filtering by family name, or to give a custom family name to generated masters.
Related to https://github.com/googlei18n/noto-source/pull/6, we want to generate separate normal/UI masters for a certain script each with it's own interpolation rules (found in Glyphs source). This seemed like the most convenient way.
> Add a "family-name" parameter to public functions

- Lib/glyphsLib/anchors.py
- Lib/glyphsLib/builder.py
- Lib/glyphsLib/builder_test.py
This makes anchor propagation (which would have failed both of the
added test cases) more robust, in response to recent updates at
https://github.com/googlei18n/glyphsLib/issues/33.
Specifically, we now a) adjust anchor positions when marks on
components were added at that anchor, not just marks on the parent
(done by recursively propagating and adjusting) and b) add ligature
anchors when there's more than one base component with a certain
anchor.
> Overhaul anchor propagation

- Lib/glyphsLib/__init__.py
- Lib/glyphsLib/parser.py
Now that kerning conflict resolution depends on the order the rules
are defined, it is always necessary to use an ordered dictionary to
store the Glyphs data.
> Always parse into ordered dictionaries

- Lib/glyphsLib/parser.py
For consistency with older Glyphs versions. Should close https://github.com/googlei18n/glyphsLib/issues/55
cc @felipesanches @behdad
> [parser] Only parse hex values up to 0xFFFF

- Lib/glyphsLib/builder.py
> builder.py: no need to decode 'copyright', etc. parser already decodes UTF-8

- Lib/glyphsLib/builder_test.py
Now that the tested code checks for a specific version number, the
default value should be something that doesn't raise any warnings.
> Add specific version number to test data

- Lib/glyphsLib/__init__.py
- Lib/glyphsLib/interpolation.py
This returns a designspace path and instance data when a designspace
is generated in the build_master function, and adds a function for
incorporating this instance data (which reflects the structure of
Glyphs source) into actual UFOs.
Ideally I'd like to take out interpolation from glyphsLib completely,
and only have options for returning master UFOs and a designspace. But
for now I'm not sure if anyone is using the interpolation feature.
> Expose more functionality for interpolating

- Lib/glyphsLib/builder.py
> Use font.lib['public.postscriptNames'] instead of glyph.lib['public.postscriptName']

- Lib/glyphsLib/interpolation.py
Some of this data will be technically incorrect for most instances,
for example the weight name and value. However, all of this incorrect
data resides in entries with a Glyphs-specific prefix and will
generally be ignored.
What we care about is the public.glyphOrder entry, which does need to
be present in any generated instance (and should be the same across a
family).
Fixes https://github.com/googlei18n/fontmake/issues/175
> [interpolation] Copy lib data to instances

- Lib/glyphsLib/builder.py
- tests/builder_test.py
Partially addresses https://github.com/googlei18n/glyphsLib/issues/85.
The next step will be to emit GlyphClassDef statements, but this can
be done independently because feaLib (just like makeotf) has built-in
heuristics to synthesize GlyphClassDef when missing.
> Emit LigatureCaretByPos statements for ligature caret positions

- Lib/glyphsLib/builder.py
- Lib/glyphsLib/casting.py
- tests/builder_test.py
Before this, only "Has WWS Names" was supported, though it was properly not checking the True/False value, but just if the custom param was present.
> set OS/2 fsSelection flags 7 and 8 from custom parameters

- Lib/glyphsLib/interpolation.py
- tests/interpolation_test.py
Before this change, the code was looking for an attribute named
`active`, but this is not what Glyphs.app stores in its files when an
instance gets marked as inactive in the Glyphs user interface. Instead,
Glyphs calls this attribute `exports` in its files.
Fixes https://github.com/googlei18n/glyphsLib/issues/129.
> Do not generate inactive instances

- Lib/glyphsLib/__init__.py
- Lib/glyphsLib/__main__.py
- Lib/glyphsLib/builder.py
- Lib/glyphsLib/glyphdata.py
- Lib/glyphsLib/util.py
- MetaTools/generate_glyphdata.py
- tests/builder_test.py
- tests/data/GlyphData.xml
- tests/data/TestGDEF.glyphs
- tests/glyphdata_test.py
Moved GlyphData.xml loading code from generate_glyphdata.py to
glyphsLib/util.py to use with custom loading.
Glyph data and therefore GDEF are now constructed by
1. Reading the default GlyphData.xml (saved in glyphdata_generated.py)
2. Reading a custom GlyphData.xml if passed
3. Reading any overrides saved in the .glyphs file
Zero the width of Nonspacing Marks when writing to UFO (like Glyphs)
As discussed in https://github.com/googlei18n/glyphsLib/issues/115 this could
be moved to ufo2ft? Also we need to check for the Glyphs custom parameter 
DisableAllAutomaticBehaviour that ignores this width zero behaviour.
Tested and looks good with Noto Sans Hebrew as reported here: 
https://github.com/googlei18n/fontmake/issues/273
Added test for loading a custom GlyphData.xml.
Added test for …
> Add command line option to pass in a custom GlyphData.xml file

- tests/data/DesignspaceTestBasic.designspace
- tests/data/DesignspaceTestFamilyName.designspace
- tests/data/DesignspaceTestInactive.designspace
- tests/data/DesignspaceTestInstanceOrder.designspace
- tests/interpolation_test.py
No change in behavior yet. This change merely updates the test input,
so that the unit tests reflect what the compiler is actually seeing
in its input sources.
https://github.com/googlei18n/fontmake/issues/167
> Use weightClass and interpolationWeight as they appear in actual fonts

- tests/data/DesignspaceTestFamilyName.designspace
- tests/data/DesignspaceTestInstanceOrder.designspace
- tests/interpolation_test.py
No changes to the implementation under test. The test output is different because
the previous test setup had stored some values into the wrong place.
> Make designspace tests less confusing

- Lib/glyphsLib/interpolation.py
- tests/data/DesignspaceTestBasic.designspace
- tests/data/DesignspaceTestFamilyName.designspace
- tests/data/DesignspaceTestInactive.designspace
- tests/data/DesignspaceTestInstanceOrder.designspace
The output files now contain the information for building `avar` tables,
and for building `fvar` tables with correct value ranges.
https://github.com/googlei18n/fontmake/issues/167
> Write variation axes into designspace documents

- Lib/glyphsLib/interpolation.py
- tests/data/DesignspaceTestTwoAxes.designspace
- tests/interpolation_test.py
Before this change, glyphsLib would produce a designspace for
NotoSansArabic-MM.glyphs that contained duplicate entries in the axis
maps. This change uniques the entries, so they're listed only once.
After this change, the generated designspace for NotoSansArabic looks
reasonable.
https://github.com/googlei18n/fontmake/issues/167
> Avoid duplicates in designspace axis maps for multi-axis fonts

- Lib/glyphsLib/interpolation.py
- tests/data/DesignspaceTestTwoAxes.designspace
The non-determinism was occasionally breaking unit tests. It was
caused by MutatorMath's DesignSpaceDocumentWriter, which iterates over
the location dictionary without sorting. The proper fix would of
course be in MutatorMath, but we'll switch to DesignSpaceDocument as
soon as that has been integrated into fonttools. So we just stop the
bleeding by passing an OrderedDict to MutatorMath.
Fixes https://github.com/googlei18n/glyphsLib/issues/165.
> Emit locations of output designspaces in deterministic order

- Lib/glyphsLib/casting.py
- Lib/glyphsLib/interpolation.py
- tests/interpolation_test.py
Fixes a regression introduced with commit https://github.com/googlei18n/glyphsLib/blob/d9d1da4e/Lib/glyphsLib/interpolation.py#L146
The 'exports' parameter was being interpreted as a string instead of as a boolean, hence the following test `if '0': ...` would always return `True`.
Notice how in line 146, the cast to `int()` was not used for the 'exports' parameter, but only for the 'active' one.
Because of this, all the instances were always generated no matter what their 'exports' value...
The tests in `interpolation_test.py` did not catch this bug, because in there we were passing an integer instead of a string as the 'exports' parameter value.
The 'exports' parameter is now explicitly being cast to boolean (db826fe).
> fix regression in detecting active instances

- Lib/glyphsLib/builder.py
- Lib/glyphsLib/casting.py
- tests/builder_test.py
Glyphs.app stores the `codePageRanges` custom parameter as a list of code page numbers, whereas UFO stores the `openTypeOS2CodePageRanges` as a list of bit numbers corresponding to codepages as per OS/2 spec:
https://www.microsoft.com/typography/otspec/os2.htm#cpr
This is the corresponding data file inside the Glyphs.app bundle:
/Applications/Glyphs.app/Contents/Frameworks/GlyphsCore.framework/Versions/A/Resources/CodePageRanges.plist
As for for `openTypeHheaCaretOffset`, it is the only one among the caret-related hhea custom parameters which is not listed in `CUSTOM_INT_PARAMS`. This causes an issue with defcon/ufoLib when setting this custom parameter (as they expects `int` but get `str`).
The other two, `openTypeHheaCaretSlopeRise` and `openTypeHheaCaretSlopeRun` are already in there.
> support codePagesRanges and openTypeHheaCaretOffset custom parameters

- Lib/glyphsLib/builder.py
- Lib/glyphsLib/util.py
- tests/builder_test.py
this converts the 'GASP Table' custom parameter to the equivalent `openTypeGaspRangeRecords` in UFO3 fontinfo.plist.
Fixes https://github.com/googlei18n/glyphsLib/issues/182
> support 'GASP Table' custom parameter

- Lib/glyphsLib/builder.py
- Lib/glyphsLib/casting.py
- tests/builder_test.py
- tests/casting_test.py
I’m not entirely sure if this is correct, but it fixes https://github.com/googlei18n/glyphsLib/issues/184 and fontmake can now process the font correctly.
> Don’t choke on QCURVE

- Lib/glyphsLib/__init__.py
- Lib/glyphsLib/__main__.py
Since these files are not supposed to be executable, there is not point
in having shebangs there. Also, since they just point to the system
python binary, they end up pointing to the wrong python version if both
python2 an python3 packages are installed for one of the python versions.
> Remove shebangs from non-executable modules

- Lib/glyphsLib/anchors.py
- tests/builder_test.py
to ensure we store them in a deterministic order on python3
Fixes #206
> Sort propagated anchors before appending

- Lib/glyphsLib/__init__.py
- Lib/glyphsLib/__main__.py
- Lib/glyphsLib/interpolation.py
When interpolating instances one may want to not round values to integers.
This can be useful when adding masters to a designspace without piling up rounding differences.
For example, if  you have 4 masters and a bunch of instances in between:
```
A-B
| |
C-D
```
And you want to interpolate new masters where instances W, X, Y, Z and R were:
```
A--W--B
|  |  |
X--R--Z
|  |  |
C--Y--D
```
You do not want to round to integers in those new masters otherwise the other instances will be too different from the original 4-master instances. Say an instance interpolated between A and B will be different from an instance interpolated between A and rounded-W or rounded-W and B, whereas it will be closer to that instance interpolated between A and non-rounded-W or non-rounded-W and B.
> Allow interpolating instances with non rounded geometry

- Lib/glyphsLib/__init__.py
- Lib/glyphsLib/parser.py
The master and classtree branches have diverged too much since v1.8.0.
Now that we have decided to go for the classtree implementation, many of the conflicting changes in master are no longer applicable to the new implementation in the classtree branch.
I'll manually cherry pick the few changes that are still relevant.
I've squashed the revert commits in a single commit to avoid cluttering the log.
> Revert master to v1.8.0 to allow merging classtree

- Lib/glyphsLib/glyphdata.py
- Lib/glyphsLib/glyphdata_generated.py
- MetaTools/generate_glyphdata.py
- tests/glyphdata_test.py
Fixes https://github.com/googlei18n/glyphsLib/issues/232
> Handle input files that use production names instead of Glyphs names

- .gitignore
- Lib/glyphsLib/__init__.py
- Lib/glyphsLib/builder/__init__.py
- Lib/glyphsLib/builder/constants.py
- Lib/glyphsLib/builder/glyphs.py
- Lib/glyphsLib/builder/ufo.py
- Lib/glyphsLib/classes.py
- Lib/glyphsLib/interpolation.py
- Lib/glyphsLib/parser.py
- Lib/glyphsLib/roundtrip.py
- Lib/glyphsLib/types.py
- Lib/glyphsLib/writer.py
- noto_pytest.ini
- tests/builder_test.py
- tests/classes_test.py
- tests/data/GlyphsUnitTestSans.glyphs
- tests/interpolation_test.py
- tests/parser_test.py
- tests/roundtrip_test.py
- tests/run_roundtrip_on_noto.py
- tests/test_helpers.py
- tests/writer_test.py
- tox.ini
@moyogo 
This is a work in progress to have full round-trip between .glyphs files and UFO3 + designspace.
Plan:
1. Add tests for the writer (GS* classes -> .glyphs file)
* Document (and fix?) small inconsistencies between the GS* classes and the Glyphs Python API documentation at https://docu.glyphsapp.com/
* Add tests for the .glyphs -> GS classes -> .glyphs round-trip (e.g. https://gist.github.com/anthrotype/3f4c9b3e04c22ddcfda196b970de8549)
2. Merge classtree + the new tests in master
In another MR:
1. Test the round-trip using the writer:
```
Test input = GSFont ------------------> designspace+UFO  ------------------> GSFont      
|     builder/ufo.py   MutatorMath+defcon   builder/glyphs.py   |         
|                                                (TODO)         | …
```
> Roundtrip .glyphs -> objects -> .glyphs

- Lib/glyphsLib/__init__.py
- Lib/glyphsLib/builder.py
Adding an argument to to_ufos() that gives control over whether propagate_font_anchors() is run. Also enables that argument to be used by load_to_ufos(), build_masters(), build_instances(). The default remains True - that propagation is done unless specifically turned off.
> Adding control over anchor propagation

- Lib/glyphsLib/classes.py
- Lib/glyphsLib/parser.py
- Lib/glyphsLib/writer.py
- tests/test_helpers.py
I took the stuff from https://github.com/googlei18n/glyphsLib/pull/213 that was worth porting over to the new classtree interface.
- make Writer only accept a single argument, the file object
- don't auto-close file, leave that to user
- handle both file objects open as binary or text
- dumps return a unicode str (like py3 json)
- Use UnicodeIO instead of StringIO to explicitly write to a unicode stream in both py2 and py3
> better handle bytes/unicode and clean up Writer api

- Lib/glyphsLib/builder/glyph.py
- Lib/glyphsLib/classes.py
- tests/builder_test.py
- tests/classes_test.py
- "Export" key must be written only when `false`
- the metrics keys were not being exported at all
- only write component's alignment and locked attributes when
any of the components in a glyph has non-default values
Part of fixing https://github.com/googlei18n/glyphsLib/issues/269
> [builder.glyph] fix writing keys to glyph.lib

- Lib/glyphsLib/types.py
- tests/types_test.py
I've been trying to batch a collection of .glyphs files using glyphsLib. whilst using it on an NDA project, it throws the following traceback
```
Traceback (most recent call last):
File "generate_variable_fonts.py", line 238, in <module>
main(sys.argv[1], sys.argv[2])
File "generate_variable_fonts.py", line 216, in main
mm_families_paths = find_mm_compatible_glyphs_files(path)
File "generate_variable_fonts.py", line 63, in find_mm_compatible_glyphs_files
glyphs_source = glyphsLib.load(glyphs_file)
File "/Users/marc/Documents/googlefonts/variable_fonts/env/lib/python2.7/site-packages/glyphsLib/parser.py", line 228, in load
return loads(fp.read())
File "/Users/marc/Documents/googlefonts/variable_fonts/env/lib/python2.7/site-packages/glyphsLib/parser.py", line 238, in loads
data = p.parse(s) …
```
> Make glyphs_datetime parse 12hr format correctly

- Lib/glyphsLib/classes.py
- Lib/glyphsLib/types.py
- tests/classes_test.py
- tests/data/GlyphsUnitTestSans.glyphs
- tests/writer_test.py
https://github.com/googlei18n/fontmake/issues/374
In Glyphs 2.5b fontMaster has "name" and "iconName" properties. The name property conflicts with the GSFontMaster name property in the parser.
> Add name setter so Glyphs 2.5b "name" property in fontMaster doesn't conflict

- Lib/glyphsLib/builder/glyph.py
- tests/builder_test.py
As mentioned here: https://github.com/googlei18n/glyphsLib/issues/116
With colors coming from outside Glyphs we were failing on `GLYPHS_COLORS[color_index]` when color_index wasn't in GLYPHS_COLORS. 
Here we should check for a tuple or a Glyphs color index and set the keys accordingly. Using the FontLab export script to make a Glyphs file results in tuples like (235,0,255,1), but the UFO spec requires integer or floats between 0 and 1 (http://unifiedfontobject.org/versions/ufo3/conventions/#colors). So check here to make sure we get what we expect. 
I'm not sure about how many decimal places we care about so put 4 for now.
> Read colors and set UFO keys for Glyphs ColorIndex and public.markColor

- Lib/glyphsLib/builder/custom_params.py
- Lib/glyphsLib/builder/features.py
- tests/builder_test.py
Second take
https://github.com/googlei18n/glyphsLib/pull/222
/cc @punchcutter
> [builder] add support for "Replace Feature" custom parameter

- Lib/glyphsLib/builder/builders.py
- tests/builder_test.py
This change detects and skips layers that are not associated with an
existing master and layers without a name. The former are a sort of data
corruption. Empty layer names are an error as per the UFO specification
and choke ufoLib. Both may happen when you copy glyphs from a different
font in Glyphs, Glyphs simply ignores them.
All invalid layers now get a warning printed and skipped. Before, they
could have been silently ignored.
Add tests for both types of bogus layers.
> Skip dangling layers and layers without a name on UFO building

- Lib/glyphsLib/builder/constants.py
- Lib/glyphsLib/builder/custom_params.py
- tests/builder_test.py
Follow up from https://github.com/googlei18n/ufo2ft/pull/186
I want to deprecate the code in fontmake that reads "com.schriftgestaltung.Don't use Production Names" UFO lib key, and handle this inside ufo2ft postProcessor using a non-glyphs-app-specific key  "com.github.googlei18n.ufo2ft.useProductionNames"
I guess @belluzj would have to convert it back to the Glyphs.app equivalent in the roundtrip branch.
> support useProductionNames lib key from ufo2ft

- Lib/glyphsLib/builder/names.py
same as we do for the 'width'.
Fixes https://github.com/googlei18n/glyphsLib/issues/300
> [builder.names] set empty weight string if 'Regular'

- MetaTools/generate_glyphdata.py
In Debian's case, we don't want to access the internet for fetching any file during build time, so we want to get rid of the license fetching as well.  We can put the license in our [debian/copyright](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/) file.
> fix: do not fetch license info when using external xml

- Lib/glyphsLib/__main__.py
As discussed here:
https://github.com/googlei18n/ufo2ft/issues/192#issuecomment-355019434
Follows fontmake’s https://github.com/googlei18n/fontmake/pull/390
> rename --no-round to --round-instances (positive), False by default

- Lib/glyphsLib/builder/builders.py
- tests/builder/builder_test.py
it can be very chatty, especially on some fonts which have tons of these
https://github.com/googlei18n/noto-source/issues/114
How often does this situation happen? It's unlikely that such name-less layers are one of the master-linked layers -- which are the ones that fontmake cares about for building fonts.
> mute "layer without name" warning if minimize_glyphs_diff=False

- Lib/glyphsLib/builder/axes.py
- Lib/glyphsLib/builder/instances.py
- Lib/glyphsLib/classes.py
- tests/builder/interpolation_test.py
- tests/data/DesignspaceGenTestItalic.designspace
- tests/data/DesignspaceGenTestRegular.designspace
- tests/data/DesignspaceTestTwoAxes.designspace
- tests/data/GlyphsUnitTestSans.glyphs
- don't write axis map elements if all input == output 
- don't write conflicting mappings (the same input maps to different outputs); if these occur (either because "Axis Location" parameters point different masters to same user-space location, or different instances have the same user-space location), then use the last occurrence but also warn the user about the mapping been redefined (would it be better to raise? see #341)
- Drop the legacy `250` value for default Thin, ExtraLight and UltraLight OS/2 weight classes. The latest Glyphs.app beta uses 100 and 200, so we do the same here.
- when setting OS/2 weight/width of UFO instances in apply_instance_data, look up weight and width axes by their tag rather than the name (which may not always be "Weight" or "Width")
> Fixes for designspace axes, and for UFO instances weight/width class

- Lib/glyphsLib/builder/features.py
- tests/builder/features_test.py
The code was trying to subscript an `ast.Comment` object before. Get the `.text` property instead for subscription.
When are we going to use type hints + mypy to catch these kinds of errors sooner? 😁
> Add tests for disabled and automatic features, fix roundtripping them

- Lib/glyphsLib/builder/sources.py
- tests/builder/designspace_gen_test.py
Found this when a colleague made a six master glyphs file, where Glyphs provides just five different weight names; he just made the two boldest ones "Bold". Before, we would  overwrite the first with the second.
> Make to target UFOs filenames unique if masters have the same style name

- Lib/glyphsLib/builder/names.py
- Lib/glyphsLib/classes.py
- tests/builder/builder_test.py
- tests/classes_test.py
This fixes a bug where Italic masters without Master Name customParameter would not have the proper master.name generated.
- GSFontMaster.name in Glyphs.app 1114 seemed to not behave properly
- Use same check for Italic as in build_style_name()
- build_style_name() is now a duplicate and is removed
> Fix GSFontMaster.name

- Lib/glyphsLib/builder/user_data.py
- Lib/glyphsLib/parser.py
- Lib/glyphsLib/types.py
- Lib/glyphsLib/writer.py
- tests/builder/lib_and_user_data_test.py
- tests/data/GlyphsUnitTestSans.glyphs
- tests/parser_test.py
The parser will no longer be able to parse and decode base64 encoded strings in .glyphs files.
And the builder will always treat the userData as hexadecimal strings when decoding to/encoding from UFO data files.
See discussion in #352 
Related issue #119  
I think if DaMa has UFO files floating around with base64 data, they can easily write a simple script to re-encode them as hexadecimal strings.
> Drop base64; always use hexadecimal strings for binary data

- .coveragerc
On Windows, stuff gets installed to e.g. `.tox/py36/lib/site-packages/glyphsLib`.
> Compile coverage data correctly on Windows

- Lib/glyphsLib/classes.py
- tests/classes_test.py
So you can pass in `Path` and friends.
> Accept os.PathLike objects in GSFont.__init__

- Lib/glyphsLib/builder/guidelines.py
- tests/builder/builder_test.py
- tests/builder/to_glyphs_test.py
The UFO3 spec has just been changed (https://github.com/unified-font-object/ufo-spec/issues/26) to acknowledge that most people and tools (specifically Glyphs and Robofont) interpret guideline angle to be CCW, despite what the spec originally stated. This provides the necessary fix and also updates appropriate tests.
> Changing guideline angle handling to reflect change in UFO3 spec

- Lib/glyphsLib/builder/builders.py
This looks like a regression from glyphsLib 2.2.1.
Previously the returned 'designspace_path' from the `glyphsLib.builder_masters` function that was used in fontmake<=1.4 would return a filename that included the custom --family-name (when provided); in glyphsLib 2.3, the designspace.filename is always set to the GSFont.familyName, regardless of whether a custom --family-name option was passed.
This is a problem because fontmake by default uses the same name as the designspace file for the output filename of the generated variable font.
When building one after the other, and to the same variable_ttf output directory, multiple Noto fonts (e.g. NotoSansBengali and NotoSansBengaliUI) which only differ from each other because of that --family-name option (i.e. they share the same .glyphs …
> default designspace.filename should use the provided custom 'family_name'

- Lib/glyphsLib/builder/custom_params.py
- requirements.txt
- tests/builder/builder_test.py
- tests/builder/instances_test.py
- tests/builder/roundtrip_test.py
- tests/builder/to_glyphs_test.py
- tests/data/DesignspaceGenTestItalic.designspace
- tests/data/DesignspaceGenTestRegular.designspace
- tests/data/DesignspaceTestBasic.designspace
- tests/data/DesignspaceTestFamilyName.designspace
- tests/data/DesignspaceTestFileName.designspace
- tests/data/DesignspaceTestInactive.designspace
- tests/data/DesignspaceTestInstanceOrder.designspace
- tests/data/DesignspaceTestTwoAxes.designspace
- tests/data/TestReencode-Regular.ufo/fontinfo.plist
- tests/data/TestReencode-Regular.ufo/glyphs/A_.alt.glif
- tests/data/TestReencode-Regular.ufo/glyphs/A_.glif
- tests/data/TestReencode-Regular.ufo/glyphs/B_.glif
- tests/data/TestReencode-Regular.ufo/glyphs/C_.glif
- tests/data/TestReencode-Regular.ufo/glyphs/D_.glif
- tests/data/TestReencode-Regular.ufo/glyphs/contents.plist
- tests/data/TestReencode-Regular.ufo/glyphs/layerinfo.plist
- tests/data/TestReencode-Regular.ufo/glyphs/space.glif
- tests/data/TestReencode-Regular.ufo/layercontents.plist
- tests/data/TestReencode-Regular.ufo/metainfo.plist
- tests/data/TestReencode.designspace
- tests/writer_test.py
fixes https://github.com/googlei18n/glyphsLib/issues/205
There is no point in attempting to roundtrip this custom parameter, since it only applies to instances (which are not meant to be convertible back to Glyphs, but only for export).
I'll add a test case later. Just want to check with @belluzj @madig or @moyogo if they think this in the right direction.
It's an issue that affect the UI variant of Noto Sans Bengali, Malayalam and Devanagari. These use a combination of "Reencode Glyphs" and "Keep Glyphs" to deal with some UI glyph variants (more compressed vertically).
> custom_params: support 'Reencode Glyphs'

- Lib/glyphsLib/__init__.py
- Lib/glyphsLib/cli.py
We use this internally because our Fontlab 5 export script does it. It was originally implemented to reduce Git merge conflicts when people inadvertently created background layers (or masks).
> Make creating background layers optional

- Lib/glyphsLib/parser.py
- tests/parser_test.py
'{unicode = 0008;}'
is parsed to:
[('unicode', 8)]
but should be:
[('unicode', '0008')]
> fix glyph's single unicode should be parsed as string, but integer

- .travis.yml
This hopefully cuts down on the awfully long setup time of pre-commit on each commit.
> Cache pip packages and pre-commit installation

- Lib/glyphsLib/builder/custom_params.py
- tests/builder/builder_test.py
- tests/builder/custom_params_test.py
Glyphs.app handles the glyphOrder parameter like UFOs: it's management is left to the user (new glyphs don't trigger a modification of the list) and non-existant glyphs are ignored (tested in Glyphs.app 2.4.1 and 2.5.2).
Remove making it a special custom parameter.
> Simplify glyphOrder handling

- Lib/glyphsLib/builder/constants.py
- Lib/glyphsLib/builder/user_data.py
- setup.cfg
- tests/builder/lib_and_user_data_test.py
- tox.ini
ufo2ft users did not like that I changed the default mode for the KernFeatureWriter to match Glyphs.app's behavior. It used to be "skip" (only add feature if not already present), but in ufo2ft v2 I changed it to "append" (add new kern lookups to existing kern feature). The idea was to support this use case:
https://glyphsapp.com/tutorials/contextual-kerning
I decided to revert the kernFeautureWriter default back to "skip". But we need to a way from glyphsLib to signal that, when building fonts from .glyphs sources with fontmake, we still wish to have the ufo2ft-generated kern feature appended to manually written kern lookups.
The solution is to store this custom glyphsLib-specific settings in the designspace lib, and have fontmake apply them when calling ufo2ft.
So, in sum, no changes …
> set custom 'append' mode for ufo2ft KernFeatureWriter 

- Lib/glyphsLib/cli.py
Prevents crash in https://github.com/googlei18n/glyphsLib/blob/master/Lib/glyphsLib/__init__.py#L112 when glyphs2ufo is launched from same directory as .glyphs file.
> Set output directory to "." if script launched in current dir and nothing is specified

- Lib/glyphsLib/builder/glyph.py
- tests/builder/to_glyphs_test.py
Python 2's round() returns a float and 3 returns an int. Use fontTools' round() and int() the result.
Fixes https://github.com/googlei18n/glyphsLib/issues/455.
> Fix converting color to glyphs:

- Lib/glyphsLib/builder/user_data.py
- tests/builder/lib_and_user_data_test.py
fontTools.ufoLib uses the fs module as a data backend, which expects POSIX paths exclusively.
Fixes https://github.com/googlei18n/glyphsLib/issues/464.
> to_ufo_master_user_data: do not modify data paths

- Lib/glyphsLib/builder/masters.py
- Lib/glyphsLib/classes.py
- tests/builder/builder_test.py
- tests/classes_test.py
Instead of crashing when finding duplicate master IDs, simply generate new ones.
Closes https://github.com/googlei18n/glyphsLib/pull/444.
> Uniquify master IDs automatically

- setup.py
- tests/builder/designspace_gen_test.py
- tests/builder/interpolation_test.py
- tox.ini
This is a proposed solution for #475, which might hopefully remove the need to continually updating test data and abandoning lightly-aged fonttools releases.
> Switch XML tests from flat comparison to xmldiff

- Lib/glyphsLib/builder/builders.py
- Lib/glyphsLib/builder/features.py
- Lib/glyphsLib/builder/font.py
- Lib/glyphsLib/builder/sources.py
- tests/builder/designspace_gen_test.py
- tests/builder/roundtrip_test.py
- tests/conftest.py
- tests/data/BraceTestFont.glyphs
This is supposed to work one-way for now (i.e. store brace layers as seperate sources in a .designspace file). Conversion of layer sources not following the brace layer convention when going to .glyphs is something for when the use case arises.
> Implement generation of brace layers in .designspace files

- Lib/glyphsLib/__init__.py
- Lib/glyphsLib/builder/__init__.py
- Lib/glyphsLib/builder/builders.py
- Lib/glyphsLib/builder/custom_params.py
- Lib/glyphsLib/cli.py
- tests/builder/roundtrip_test.py
When working collaboratively, storing editor state is counter-productive and can lead to merge conflicts.
> Add CLI option to store (or not) editor state

- tests/builder/designspace_gen_test.py
Fixes test runs on Windows, where paths tripped up the parser.
> designspace_gen_test: Correctly read test files

- Lib/glyphsLib/builder/builders.py
- Lib/glyphsLib/builder/glyph.py
- Lib/glyphsLib/util.py
- tests/builder/designspace_gen_test.py
- tests/data/BracketTestFont.glyphs
This PR does the following:
- When going from .glyphs to UFO, extract bracket layers into specially named, free-standing glyphs that can be referenced from a .designspace.
- When going back to Glyphs, put the layers back and remove the free-standing glyphs.
Todo:
> WIP: Support bracket layers

- Lib/glyphsLib/__init__.py
Do it like fontmake in https://github.com/googlei18n/fontmake/commit/5696415ff47a064d75da99d0d209688d48f95127.
> build_masters: remember written fonts instead of filtering source layers

- Lib/glyphsLib/builder/custom_params.py
- Lib/glyphsLib/builder/filters.py
- Lib/glyphsLib/builder/user_data.py
- tests/builder/custom_params_test.py
Currently, `ufo2glyphs` with a `com.github.googlei18n.ufo2ft.filters` lib key crashes. Fixing the immediate crash shows that in the Glyphs file, you end up getting multiple `PreFilter`s with one letter of the filter name each. The `include` part isn't included. Fixing that shows that the filters are doubled on roundtripping back to UFOs.
> Roundtrip ufo2ft filters correctly

- Lib/glyphsLib/builder/axes.py
- tests/data/DesignspaceTestTwoAxes.designspace
Possible improvement on the situation in https://github.com/googlei18n/fontmake/issues/470
@anthrotype
> Use the OS/2 width class to map the wdth axis

- Lib/glyphsLib/classes.py
- Lib/glyphsLib/parser.py
- Lib/glyphsLib/types.py
- tests/classes_test.py
- tests/data/IntegerFloat.glyphs
- tests/parser_test.py
When round-tripping, integer coordinates in .glyphs files end up being floats in the UFO.
It seems to happen when parsing .glyphs files.
> Integers stay integers

- Lib/glyphsLib/builder/builders.py
- Lib/glyphsLib/builder/features.py
- Lib/glyphsLib/builder/glyph.py
- tests/builder/builder_test.py
https://github.com/googlei18n/glyphsLib/issues/515.
Handling this well in a oh-please-not-more-technical-debt kind of way is tricky.
There are three ways to signal that a glyph should not be exported:
1. The old `com.schriftgestaltung.Glyphs.Export` glyph lib key
2. The new UFO-level `public.skipExportGlyphs` lib key
3. The new Designspace-level `public.skipExportGlyphs` lib key
ufo2ft will look into the Designspace lib key when using the `compile*FromDS` functions and into the UFO-level lib keys with the other `compile*` functions. Writing only to the Designspace-level lib key may complicate e.g. fontmake, which uses `glyphsLib.to_designspace` to convert a .glyphs file into DS + UFOs, but uses `compile*` or `compile*FromDS` depending on what the user specifies on the CLI.
Proposed …
> Support public.skipExportGlyphs lib key for storing export flags

- Lib/glyphsLib/__init__.py
- Lib/glyphsLib/builder/__init__.py
- Lib/glyphsLib/builder/builders.py
- Lib/glyphsLib/builder/features.py
- Lib/glyphsLib/builder/glyph.py
- Lib/glyphsLib/cli.py
- tests/builder/builder_test.py
- tox.ini
The lib key is now supported alongside the old glyph level lib key, to avoid disruption in fontmake etc. until feature subsetting from `public.skipExportGlyphs` is implemented.
Todo:
> Support UFO's `public.skipExportGlyphs`, take two

- Lib/glyphsLib/builder/axes.py
- tests/data/DesignspaceTestTwoAxes.designspace
This restores #451, which I had reverted before releasing v3.3.1
Since this is a breaking change I propose we bump major version to v4.0
> use OS/2 width class to map instances' user/design locations

- Lib/glyphsLib/builder/builders.py
- tests/builder/designspace_gen_test.py
- tests/data/BracketTestFont2.glyphs
Prompted by https://github.com/googlefonts/glyphsLib/issues/535, I decided to work on completing the bracket layers support started in https://github.com/googlefonts/glyphsLib/issues/468.
This adds support for
- "reverse" bracket layers (e.g. `]500]`) where the location represent the range's maximum, as opposed to regular bracket layers (`[500]`) where value indicates a minimum. 
- what Nikolaus called "unbalanced" bracket layers, i.e. when only some of master layers have explicilty defined bracket layers. The missing master layers are implicitly duplicated as bracket layers.
- composite glyphs with bracket layers that match the definition of their components' bracket layers (#535): the components' base glyphs need to be adjusted accordingly.
The PR is marked as WIP because next week I …
> [bracket layers] support reverse, unbalanced and composite glyphs

- .travis.yml
- Lib/glyphsLib/glyphdata.py
- setup.cfg
`__file__` attribute is not set on modules when they are embedded in zip files or in self-contained executables such as those built with PyOxidizer.
The recommended way to load resource files (i.e. the ones specified in ``package_data`` in setup.py) is by using the `importlib.resources` API, which was added in Python 3.7.
For < 3.7 we require the backport 'importlib_resources' which is available on PyPI.
Also:
- in glyphdata module we import `unicodedata` to look up categories; we can import `fontTools.unicodedata` which opportunistically uses `unicodedata2` when available (so we can get more up-to-date UCD than the built-in one on older pythons).
- setup.cfg `install_requires` needs to explicitly require `fonttools` with the `[ufo]` extra, which in turn is required by `defcon`...
>  glyphdata: use importlib.resources instead of __file__

- Lib/glyphsLib/__init__.py
- Lib/glyphsLib/builder/__init__.py
- Lib/glyphsLib/builder/anchors.py
- Lib/glyphsLib/builder/blue_values.py
- Lib/glyphsLib/builder/builders.py
- Lib/glyphsLib/builder/custom_params.py
- Lib/glyphsLib/builder/features.py
- Lib/glyphsLib/builder/glyph.py
- Lib/glyphsLib/builder/instances.py
- Lib/glyphsLib/builder/layers.py
- Lib/glyphsLib/cli.py
- Lib/glyphsLib/util.py
- requirements-dev.txt
- requirements.txt
- setup.cfg
- tests/builder/axes_test.py
- tests/builder/builder_test.py
- tests/builder/custom_params_test.py
- tests/builder/designspace_gen_test.py
- tests/builder/designspace_roundtrip_test.py
- tests/builder/features_test.py
- tests/builder/fontinfo_test.py
- tests/builder/instances_test.py
- tests/builder/interpolation_test.py
- tests/builder/lib_and_user_data_test.py
- tests/builder/roundtrip_test.py
- tests/builder/to_glyphs_test.py
- tests/conftest.py
- tests/run_various_tests_on_various_files.py
- tests/test_helpers.py
use ufoLib2 by default -- but still allow to use defcon (or a compatible UFO library) as the `ufo_module` in build_masters, to_designspace, to_ufos, etc.
glyphs2ufo also has a new `--ufo-module` option.
> add support for ufoLib2 (in addition to defcon)

- Lib/glyphsLib/builder/features.py
- tests/builder/features_test.py
unlike defcon.Font, ufoLib2 doesn't auto append new glyphs to the glyphOrder. Thus, if the public.glyphOrder list is incomplete and some glyphs are not in that list, attempting to call `ufo.glyphOrder.index(glyph_name)` may fail with ValueError.
We need to handle this gracefully by sorting these glyphs-outside-glyphOrder alphabetically, after the explicitly ordered ones.
> features:_build_gdef: handle glyphs outside ufo.glyphOrder

- Lib/glyphsLib/builder/layers.py
- tests/builder/builder_test.py
Glyph sub layers are sometimes duplicated in Glyhps.app source files.
For example if a user double-clicks on "Copy layer"  or for other reasons, a glyph "a" may have two glyph layers called "Dec 16 19, 12:00". Writing the UFO will fail when trying to write the glyph to "Dec 16 19, 12:00" twice.
This PR "solves" this by renaming the second layer, adding " #1", or " #n+1" .
> Rename glyph layers when duplicate

- .pre-commit-config.yaml
- Lib/glyphsLib/builder/glyph.py
- Lib/glyphsLib/builder/paths.py
- Lib/glyphsLib/builder/user_data.py
- Lib/glyphsLib/classes.py
- Lib/glyphsLib/types.py
- Lib/glyphsLib/util.py
- Lib/glyphsLib/writer.py
- tests/builder/builder_test.py
- tests/builder/features_test.py
- tests/builder/fontinfo_test.py
- tests/builder/lib_and_user_data_test.py
- tests/builder/to_glyphs_test.py
- tests/classes_test.py
- tests/writer_test.py
I discovered https://github.com/nvdv/vprof and used it to run this script (Cantarell from https://gitlab.gnome.org/GNOME/cantarell-fonts/tree/dd36d229a2c304d17052dd62ad959f4e210c3c75/src):
```Python
import glyphsLib.cli
glyphsLib.cli.main(["ufo2glyphs", "Cantarell.designspace"])
```
Fedora 31 x64, Python 3.7.5, Ryzen 1700, all data in /tmp, which is a RAM-based tmpfs.
I tackled `GSNode._indices()` and `floatToString`.
After not calling `_indices()` on every node:
After simplifying `floatToString`:
That shaved off roughly 1 second, so it's a ~25% speed up :)
> Profile guided performance optimization

- Lib/glyphsLib/builder/custom_params.py
- Lib/glyphsLib/builder/font.py
- tests/builder/builder_test.py
Closes https://github.com/googlefonts/glyphsLib/issues/560.
The idea is to not be smart and copy `public.GlyphOrder` to the Font's custom parameters verbatim and back if it exists.
> Copy glyphOrder lib key/custom parameter verbatim

- Lib/glyphsLib/builder/components.py
- tests/builder/builder_test.py
Glyphs exports anchor and alignment data in this key. Also makes import not fail
anymore when it's used only for alignment and no anchor info present and
with bogus data.
Closes #532.
> Use ComponentInfo for `alignment`, make reading it more robust

- Lib/glyphsLib/glyphdata.py
- tests/glyphdata_test.py
GlyphsLib fails to detect the category of glyphs like `dal_alef-ar` that GlyphsApp correctly classifies as Letter, Ligature.
> glyphdata: Handle ligatures with suffix

- Lib/glyphsLib/builder/axes.py
- tests/builder/axes_test.py
- tests/data/AxesWdth.glyphs
- tests/data/AxesWdthWght.glyphs
Add yet another heuristic to prevent a glyphs2ufo edge case where you have a single master at the default location and end up with a Designspace with no axes. If you have an Axes parameter, try to put the axes mentioned in there into the Designspace.
> Keep Axis axes

- Lib/glyphsLib/builder/axes.py
I pushed a failing test case in https://github.com/googlefonts/glyphsLib/commit/c5d7ce8fef9ace91107ee8ef9e0f2a4a6a63629c
https://travis-ci.org/github/googlefonts/glyphsLib/jobs/670207208
Fixes https://github.com/googlefonts/fontmake/issues/644
> axes: add no-op weight axis when no other interesting axes

- Lib/glyphsLib/builder/builders.py
- Lib/glyphsLib/builder/components.py
- Lib/glyphsLib/classes.py
- tests/builder/components_test.py
- tests/data/Recursion.glyphs
This PR decomposes components used in background layers when going glyphs2ufo.
The UFO v3 and Glyphs data model have incompatible component reference semantics. UFO components always point to a glyph in the same layer, Glyphs components in a ...:
- master layer: point to glyphs in the same master layer, like in the UFO format.
- non-master layer: point to glyphs in the layer with the same layer name and fall back to glyphs in the associated master layer
Limit to background layers for now because functional layers like bracket and brace layers can contain components, too, and need special but too time-consuming handling. Non-functional layers like the copies you can make in Glyphs' UI with the "+" in the layer pane are likewise ignored. Bracket layers are already flattened in UFOs.
Closes …
> Decompose background layers

- Lib/glyphsLib/builder/axes.py
- Lib/glyphsLib/builder/masters.py
- Lib/glyphsLib/builder/sources.py
- tests/builder/axes_test.py
Support the 'Axis Mappings' customParameter.
If this customParameter has been defined, it takes precedence over all our other methods to assemble the designspace axes.
Todo:
- Possibly add a more informative comment
- regularDesignLoc and regularUserLoc are copy pasta. We may want to refactor this.
> Support 'Axis Mappings' customParameter

- Lib/glyphsLib/builder/builders.py
- tests/builder/axes_test.py
Problem: during `to_designspace` execution in the `to_glyphs`, `to_designspace` roundtrip, an error occurs when a custom axis contains no mappings.
`ValueError: min() arg is an empty sequence`
This occurs because Glyphs.app does not store an axis' `minimum`, `maximum` and `default` values, and therefore these values are wiped during `to_glyphs` conversion. Normally, `to_designspace` recalculates these values using the sources and the axis' mapping values. However if there are no mappings in the axis, `to_designspace` will error.
This error can be avoided by adding identity mappings to the designspace, as `to_glyphs` will keep these mappings, which then provides `to_designspace` with the required mappings it needs to calculate the minimum and maximum values of the custom axis. However, …
> Fix problem where axis with no mappings was erroring out during roundtrip

- Lib/glyphsLib/classes.py
- tests/classes_test.py
- tests/writer_test.py
Matches Glyphs App API and for consistency with the rather identical GSFont.classes.
> Use Proxy for GSFont.features/featurePrefixes

- Lib/glyphsLib/classes.py
- tests/classes_test.py
When trying to run a Glyphs script on the command line, I noticed that I couldn't set a node's position. Glyphs allows `n.position = (x,y)`, but this creates a tuple when GSNode expects a `Point` object. But of course I can't use a `Point` object because then the script wouldn't work in Glyphs...
This PR allows setting `n.position = (x,y)` and automatically upcasting that to a `Point` object.
> Improve compatibility with Glyphs

- Lib/glyphsLib/builder/axes.py
- tests/builder/axes_test.py
Previously, wght and wdth would be forcibly be made first.
> ufo2glyphs: preserve DS axis order

- Lib/glyphsLib/builder/builders.py
- Lib/glyphsLib/builder/glyph.py
- tests/builder/designspace_gen_test.py
- tests/data/PSNames.glyphs
When a Glyphs glyph has a production name set, any bracket glyph detaching from it will inherit it unchanged, when it should also get its BRACKET suffix.
> Make sure that detaching bracket glyphs get their own production name

- Lib/glyphsLib/builder/features.py
- tests/builder/features_test.py
- tests/data/CommentedClass.glyphs
This adds a newline to before the closing bracket of a class definition. Why do we want to do this? Well, there's an obscure corner case I just hit today.
Glyphs allows comments in glyph classes like so:
If the last entry in a glyph class is commented out, glyphsLib writes a UFO feature file like so:
```
@Test = [ A
```
The closing bracket of the class is commented out, causing a syntax error.
This PR writes the feature as
```
@Test = [ A
];
```
instead.
> Fix commented class issue

- Lib/glyphsLib/builder/hints.py
- tests/classes_test.py
- tests/data/GlyphsUnitTestSans.glyphs
See *Hints: handle up and down targets* https://github.com/googlefonts/glyphsLib/issues/376
> hints: target="up" or "down"

- Lib/glyphsLib/builder/builders.py
- Lib/glyphsLib/builder/constants.py
- Lib/glyphsLib/builder/layers.py
- Lib/glyphsLib/builder/user_data.py
- tests/builder/lib_and_user_data_test.py
- tests/builder/to_glyphs_test.py
The layer name [`public.default`](https://unifiedfontobject.org/versions/ufo3/layercontents.plist/#publicdefault) *indicates that the default layer has no user defined name*.
glyphsLib should store the user defined default layer name and round-trip it to UFOs.
The layer lib is now stored in the master userData instead of the font userData.
When several UFOs each have a layer with the same name, their lib may be different and cannot be stored in the font userData under the same key.
This now uses `master.userData["com.schriftgestaltung.Glyphs.layerLib.<layer.name>"]["com.schriftgestaltung.Glyphs.layerName"]`, one per layer, instead of `font.userData["com.schriftgestaltung.Glyphs.layerLib.<layer.name>"]["com.schriftgestaltung.Glyphs.layerName"]`, one for all layers with the same name across …
> UFO default layer with custom name

- Lib/glyphsLib/builder/font.py
- Lib/glyphsLib/filters/eraseOpenCorners.py
- requirements-dev.in
- requirements-dev.txt
- requirements.txt
- tests/eraseOpenCorners_test.py
Requires https://github.com/fonttools/fonttools/pull/2192 to be merged. Fixes #255 and https://github.com/googlefonts/fontmake/issues/288
> Close open corners in UFO

- .github/workflows/regression.yml
This reverts commit 6bccbff8426c45ceb1a73bc5a654e4d81c42e14a.
Now that the new code and scripts have landed, we can use main as a point of reference.
> Revert "Ignore main branch for now"

- setup.cfg
Fixes #701
When using setuptools (commonly still used for distro packages because no other
solution supports installing to bare packaging directory yet) to build a project
it is not necessary or desired to have *wheel* in the loop. It is needed for
releasing the project upstream of course, but not for installing it locally.
> Do not require wheel for all setuptools operations

- Lib/glyphsLib/builder/tokens.py
Identified in #719 CI test runs (e.g., https://github.com/googlefonts/glyphsLib/pull/719/checks?check_run_id=3620803347)
> flake8 lint: refactor chained exception to use `from`

- Lib/glyphsLib/parser.py
- tests/parser_test.py
Workaround for the FontLab 7 glyphs source export trailing semicolon that raises an error on fontmake compiles as noted in https://github.com/googlefonts/fontmake/issues/806.
> Accept FL7 trailing semicolons

- Lib/glyphsLib/filters/eraseOpenCorners.py
- tests/eraseOpenCorners_test.py
This is more of a bandaid, but it seems more hygienic to not re-draw a glyph we claim is not modified by the filter.
Fixes https://github.com/googlefonts/glyphsLib/issues/710
> Don’t re-draw glyph if no overlap was removed

- Lib/glyphsLib/classes.py
`Writer()` defaults to format version 2 and `GSFont.save()` did not set version on the `Writer` object making it think it is saving format 2 regardless of the font format.
> Fix saving version 3 fonts

- Lib/glyphsLib/builder/custom_params.py
The property name is plural, `sampleTexts`, not singular.
> Fix converting sampleText from version 3 fonts

- Lib/glyphsLib/builder/custom_params.py
In Glyphs 3 the custom parameter is “gasp Table” instead of “GASP table”. I’m not sure how to register custom parameter handler based on
format version, so I simply duplicated the handler with the new name even though that means both would be active for any format version (I’m personally fine with that).
> Fix converting gasp table from version 3 fonts

- Lib/glyphsLib/builder/custom_params.py
`vendorID` is not a custom parameter any more.
> Fix converting vendorID from version 3 fonts

- Lib/glyphsLib/builder/glyph.py
- tests/builder/builder_test.py
In minimal mode we need to skip no export glyphs when exploding color layers otherwise ufo2ft will fail building the font since it does not
seem to filter the `colorLayers` key.
> [builder] Skip color layers for no export glyphs

- .github/workflows/ci.yml
- Lib/glyphsLib/glyphdata.py
- README.rst
- setup.cfg
- tox.ini
3.10 is out next week, while 3.6 reaches end of life at the end of this year.
It's time to require 3.7 or greater, so we can finally use built-in dataclasses and more.
> drop Python 3.6, require >= 3.7

- .pre-commit-config.yaml
The default virtualenv is faster.
> pre-commit: No need to use venv anymore

- Lib/glyphsLib/builder/components.py
- Lib/glyphsLib/builder/glyph.py
- Lib/glyphsLib/builder/layers.py
- Lib/glyphsLib/builder/sources.py
- Lib/glyphsLib/classes.py
- tests/builder/builder_test.py
- tests/builder/designspace_gen_test.py
- tests/data/BraceTestFontV3.glyphs
Glyphs 3 has explicit layer attributes for things that Glyphs 2 used magic layer names for, and layer names has no special meanings. We often check for layer attributes and unconditionally fallback to layer name, but this can lead to undesired effects when layer names in Glyphs 3 happen to match magic Glyphs 2 names.
To fix this we now check for layer attributes in Glyphs 3 and layer names in Glyphs 2.
> Handle Glyphs 3 layer attributes a bit better

- Lib/glyphsLib/builder/features.py
- Lib/glyphsLib/classes.py
- tests/builder/builder_test.py
- tests/builder/features_test.py
The special feature note from Glyphs
```
Name: Single-storey a
```
will be exported to
```afdko
featureNames {
name "Single-storey a";
};
```
Fixes #602
> Export special feature note to featureNames

- .github/workflows/ci.yml
Ii was inadvertently removed in 03392eb.
Fixes https://github.com/googlefonts/glyphsLib/issues/752
> [ci] Restore Codecov upload

- Lib/glyphsLib/__init__.py
We were not passing glyph_data to the builder functions.
> [cli] Make passing --glyph-data actually do something

- Lib/glyphsLib/builder/color_layers.py
- tests/builder/builder_test.py
Apparently comparing layer objects is not reliable. Comparing layer ID with master ID instead.
> [builder] Fix re-use of master layer in color glyphs

- Lib/glyphsLib/classes.py
* The key "default" is sometimes used as a default language value
* You can't index into a `dict_values`.
Found while investigating #746
> Fix two small problems with localised values

- Lib/glyphsLib/builder/glyph.py
- tests/builder/builder_test.py
When a master layer has color attributes, we try to avoid creating a duplicate color layer of it. This was broken if the layer had multiple
paths with with different color attributes each. Fix this by returning the layer only when the new layer has the same number of paths and
components, and create a new layer otherwise.
> [builder] Fix color on master layer optimization

- Lib/glyphsLib/builder/axes.py
Ensures that `class_to_value` is run on the width value coming from Glyphs 3 source files. Fixes #780.
> Remap G3 width class to user value

- Lib/glyphsLib/builder/glyph.py
- Lib/glyphsLib/builder/kerning.py
- Lib/glyphsLib/classes.py
- tests/data/SpecialLayerWidth.glyphs
- tests/specal_layer_width_test.py
For https://github.com/googlefonts/glyphsLib/issues/773
```
```
It says `may`, but then the metrics are copied regardless. I added a condition.
> Retain intermediate layer width correctly

- Lib/glyphsLib/builder/builders.py
- tests/builder/designspace_gen_test.py
Glyphs has a mechanism (the "Feature for Feature Variations" custom parameter) for setting which feature should be used for processing bracket rules. This implements that custom parameter, passing the feature information to designspace. If the user requests `rclt`, we set `processing=last` on the rules tag; otherwise, we use the equivalent designspace lib key `com.github.fonttools.varLib.featureVarsFeatureTag`.
> Set feature for designspace rules

- Lib/glyphsLib/builder/constants.py
- Lib/glyphsLib/builder/custom_params.py
- tests/builder/custom_params_test.py
Closes #693.
- Convert "meta Table" to public.openTypeMeta
- Tests for meta table implementation
> Support "meta Table" custom parameter

- Lib/glyphsLib/builder/axes.py
- Lib/glyphsLib/classes.py
- tests/builder/axes_test.py
- tests/data/VariableInstance.glyphs
Glyphs 3 implemented a new type of instance for VF settings that sits alongside the known type of "normal" instances.
This messed with the `instance_mapping` creation in `axes.py` as it would overwrite `designLoc` back to `0` for the `Regular` instance, causing the designspace to have erroneous default locations.
This PR now excludes the "variable" instance from being processed for the `instance_mapping` creation.
Edit: This is kind of urgent, as a new version of Cairo Play needs to be published. I can't temporarily use this branch for the font because I already have to use other temporary branches in order to be able to generate RTL kerning. Issues are piling up for Arabic. This PR here is a quick one.
> exclude GSInstance.type == "variable" when building DS axis maps

- Lib/glyphsLib/classes.py
If a G2 file is saved with `format_version=3`, currently all its master names get reset to Regular. This fixes that.
> Write master names when writing v3 version

- Lib/glyphsLib/builder/axes.py
- Lib/glyphsLib/classes.py
Small fixup for #812 and #813.
- Use constants in API, as Glyphs does (see https://docu.glyphsapp.com/#instance-types)
- Check against constant when deciding to include an "instance" (i.e. VF setting) in the axis mappings
> VF settings fixup for #812/#813

- Lib/glyphsLib/builder/custom_params.py
- Lib/glyphsLib/classes.py
- tests/builder/custom_params_test.py
We have some Glyphs source files with custom name table entries that weren't preserved when converting to UFO. This PR parses the Glyphs `<nameid> <platform_id>? <encoding_id>? <language_id>?; <string>` format and creates UFO `openTypeNameRecords` (and vice versa).
I added a new test that covers all the different combinations the Glyphs name table entry format supports. In the case the Glyphs name table entry only specifies a name identifier and string default values are used for the other parameters. The default parameters are not removed when converting from UFO -> Glyphs, so roundtripping a Glyphs will not be literally identical but functionally identical.
This is a partial fix for #633.
> [review] Add support for roundtripping Glyphs/UFO custom name table entries.

- Lib/glyphsLib/builder/smart_components.py
- Lib/glyphsLib/classes.py
Using `pickle` was indeed faster than using `deepcopy`, but it's still slower than shallow-cloning each node. This should speed up the regression tests significantly (and anything that uses smart components).
Also a slightly more helpful error message when a smart component is not interpolatable.
> Smart component speedup

- Lib/glyphsLib/builder/builders.py
- tests/builder/designspace_gen_test.py
Fixes the *other* issue with Playfair Italic in #741. Alternate layers may be unnamed because Glyphs does not rely on (or even display) the user-supplied name for them, and we make up our own name for them anyway.
> Allow alternate layers to be unnamed

- Lib/glyphsLib/classes.py
Glyphs 3 sometimes stores the alternate glyph min/max coordinates as strings, for a bit of variety. See #741.
> Ensure alternate glyph rules are floats

- Lib/glyphsLib/builder/bracket_layers.py
- Lib/glyphsLib/builder/builders.py
- Lib/glyphsLib/builder/glyph.py
- tests/builder/builder_test.py
- tests/builder/designspace_gen_test.py
- tests/data/BracketTestFont2.glyphs
- tests/special_layer_width_test.py
This fixes as much of #837 as I'm prepared to fix. It deals with the situation of parent glyphs which have no alternate layers but use component glyphs which do have alternate layers.
It doesn't deal with the situation of parent glyphs which have alternate layer setups which differ from those of their component glyphs, but it has a decent stab at it and warns the user. (Those are pretty rare, anyway. In the situation of Playfair 3 which had 633 "problematic" layers, only 8 of them were in this category.)
It also deals with my obviously short-sighted approach to glyph naming for alternate layers. Instead of producing long names like `_f_ydieresis.ligature.BRACKET.opsz_5_410.wdth_50_75.wght_690_900`, it now just numbers them.
> More alternate layer fixes

- Lib/glyphsLib/classes.py
- tests/writer_test.py
Same as https://github.com/googlefonts/glyphsLib/pull/835 but checks the format version instead of looking in both places and avoids storing/writing it twice.
Prior to Glyphs 3, smart component information was stored in a `userData` key; in Glyphs 3 format, it's stored in the `partSelection` slot of the layer itself. We need to look in either places depending on the GSFont's format_version.
> Support finding smart component info in G3 format (2)

- Lib/glyphsLib/builder/bracket_layers.py
So it turns out that #841 was caused by the fact that `[()]` is True, and so boxes were getting added to the list of layers to synthesise even if there wasn't actually any alternate-layer information in the layer.
> Only add box to box list if there's actually a box

- Lib/glyphsLib/__init__.py
- Lib/glyphsLib/builder/__init__.py
- Lib/glyphsLib/builder/builders.py
- Lib/glyphsLib/builder/features.py
- Lib/glyphsLib/cli.py
- tests/builder/features_test.py
As suggested in https://github.com/googlefonts/glyphsLib/issues/797, it may be useful sometimes to resolve and expand include statements in features, to create self-contained UFOs/glyphs sources that don't reference any external files. It is disabled by default, to make sure rountripping continues to work. It is not conflated with 'minimal' option because they are distinct things, one may want to enable one without the other.
fontmake may use this to `--expand-features-to-masters` (e.g. when doing `fontmake -o ufo`) similarly to the existing `--expand-features-to-instances` option. However, to fix #797, I prefer to override the include directory (https://github.com/googlefonts/fontmake/pull/917).
> add option to both UFO|GlyphsBuilders to expand_includes in features

- Lib/glyphsLib/builder/instances.py
- tests/builder/axes_test.py
- tests/data/VariableInstance.glyphs
#813 resp. its PR #812 did only skip "variable font setting" instances when building the axis mappings.
This PR actually keeps them out of the designspace file. I've also adapted the test.
> Vf settings fixup 2

- Lib/glyphsLib/builder/custom_params.py
- tests/builder/builder_test.py
- tests/regression_test.py
When `glyphOrder` custom parameter is used with partial glyph coverage, Glyphs will use the .glyphs glyph order for the rest of the glyphs, while ufo2ft will sort the glyphs alphabetically. Fix this inconsistency by always making sure UFO `public.glyphOrder` has full coverage.
> Fix glyph order for custom parameter with partial coverage

- Lib/glyphsLib/builder/custom_params.py
According to the [specification], platform ID 3 is Windows, not Unicode. I have also synched the other comments with the specification. In the [handbook], it is sloppily written as follows, which could be the source of confusion:
> If not specified, platformID will be assumed as 3, and successively, encID as 1 (Unicode), and langID as 0×0049 (Windows English).
[handbook]: https://glyphsapp.com/media/pages/learn/3ec528a11c-1634835554/glyphs-3-handbook.pdf
[specification]: https://learn.microsoft.com/en-us/typography/opentype/spec/name#platform-ids
> Make comments follow the specification (custom parameters)

- Lib/glyphsLib/classes.py
- tests/glyphs3_test.py
This implements writing `postscriptBlueValues`, `postscriptOtherBlues`, `postscriptStemSnapV` and `postscriptStemSnapH` for glyphs > ufo.
I added [./tests/glyphs3_test.py](tests) and other tests are passing as well.
I'm not sure how elegant or clumsy it is to have those `GSFontMaster._...` underscore internals and accessing them via the getter/setter proxies, but it seemed the most practical way synthesize them from the `GSFont` attributes required for the offsets.
There are [this](https://github.com/kontur/glyphsLib/blob/fc2b551ddd02da4df0f0b2290fc526a554108847/Lib/glyphsLib/classes.py#L1765), [this](https://github.com/kontur/glyphsLib/blob/fc2b551ddd02da4df0f0b2290fc526a554108847/Lib/glyphsLib/classes.py#L1799) & [this](https://github.com/kontur/glyphsLib/blob/fc2b551ddd02da4df0f0b2290fc …
> Implements part of #754 via getter/setters for proxying the file format 3 attributes

- Lib/glyphsLib/classes.py
- tests/writer_test.py
When using `glyphsLib` for manipulating Glyphs files, it produces a lot of unrelated changes due to its serialization order that is different from the one used by Glyphs. This PR is an attempt to reduce the different.
> Reduce the ordering difference with respect to Glyphs

- Lib/glyphsLib/classes.py
- tests/builder/instances_test.py
> Serialize instance properties

- Lib/glyphsLib/builder/custom_params.py
- tests/builder/custom_params_test.py
There is arguably the following error in both the Glyphs [handbook](https://glyphsapp.com/media/pages/learn/3ec528a11c-1634835554/glyphs-3-handbook.pdf) and the UI:
> If not specified, platformID will be assumed as 3, and successively, encID as 1 (Unicode), and langID as 0×0049 (Windows English).
It is meant to say that the language is set to 0x409. This is what Glyphs does upon export. Moreover, 0x49 is not a valid language ID as far as the [specification](https://learn.microsoft.com/en-us/typography/opentype/spec/name#windows-language-ids) is concerned.
/cc @schriftgestalt
> Fix a typo in the default behavior of naming-table entries

- Lib/glyphsLib/builder/groups.py
- Lib/glyphsLib/builder/kerning.py
- tests/data/RTL_kerning_v2.glyphs
- tests/data/RTL_kerning_v3.glyphs
- tests/glyphs3_test.py
This is adapted from @simoncozens' https://github.com/simoncozens/dumbifier/blob/main/Lib/dumbifier/rtl_kerning.py
see discussion in https://github.com/google/fonts/pull/5924#issuecomment-1441925247
~~The tests _don't_ work though yet...~~ (edit: they do now)
> 3rd attempt at fixing RTL kerning export

- Lib/glyphsLib/builder/font.py
- Lib/glyphsLib/builder/glyph.py
- Lib/glyphsLib/builder/hints.py
- Lib/glyphsLib/filters/cornerComponents.py
- tests/corner_components_test.py
- tests/data/CornerComponents.glyphs
Smart components were easy! Corner components... not so much. I don't quite understand how they work. But once I *do*, here's a framework for getting them implemented:
* Export them as hints (which we do already) in the UFO, ensuring we pass along the hint's name (since this is the name of the corner component glyph).
* Add a custom filter to "apply" those hints, by modifying the glyphs' path.
* Convert the hints into a sensible data structure
* ???
* Profit!
> Implement corner components

- Lib/glyphsLib/builder/instances.py
- tests/builder/interpolation_test.py
For compatibility with Adobe apps we maintain strict backwards compatibility for postscript names (name ID 6) in all our families. To achieve this, we explicitly set the `postscriptFontName` in UFO and Glyphs files. However, we noticed that for some fonts generated from Glyphs files the postscript name was auto generated regardless of the Glyphs `Font Name` setting.
It seems that in Glyphs v2 format, the `postscriptFontName` property was stored in `customParameters`, but for the Glyphs v3 format it is stored in `properties`. The code that generates instances only looks at `customParameters`, so any Glyphs format v3 file with a custom postscript name will receive an auto-generated postscript name instead.
This pull request modifies the instance generation code to also check the …
> Use postscriptFontName from Glyphs format v3 when generating instances.

- Lib/glyphsLib/parser.py
- tests/data/GlyphsUnitTestSans3.glyphspackage/order.plist
- tests/glyphs3_test.py
In https://github.com/googlefonts/glyphsLib/issues/846#issuecomment-1478023500, Georg said
> But was in really intended to load the .glif file based on the name? I thought that you should read all files and map them based off the name in the file?
This PR does that: loads all files in the `glyphspackage` directory and then reorders them based on the order in `order.plist`.
> Load all .glyphspackage glyphs

- Lib/glyphsLib/builder/custom_params.py
- tests/builder/custom_params_test.py
- tests/data/UFOInstanceParametersTest.glyphs
- tests/data/UFOInstanceParametersTestV2.glyphs
- tests/data/UFOInstanceParametersTestV3.glyphs
Given that `properties` always exists in `GSInstance`s, the conversion to UFO never considers `customParameters` as a source for preferred family names among others. Custom parameters, however, are the primary mechanism in version 2, which means the current code does not work for version 2.
This pull request proposes to always fall back to custom parameters.
> Fall back from properties to custom parameters

- Lib/glyphsLib/builder/custom_params.py
- tests/builder/custom_params_test.py
- tests/data/UFOInstanceParametersTestV2.glyphs
- tests/data/UFOInstanceParametersTestV3.glyphs
When font selection flags are specified on the level of both the font (the tab) and instance, the ones in the former get discarded. This pull request switches from resetting to merging (union).
> Merge font selection flags from the font and instance

- Lib/glyphsLib/builder/tokens.py
- tests/data/TokenTest.glyphs
- tests/tokens_test.py
See Glyphs 3 handbook.
Currently only width and anchors properties work, if our GSLayer starts supporting LSB, RSB, TSB, and BSB, they should magically work here as well.
> Support glyph property tokens

- Lib/glyphsLib/classes.py
- tests/builder/custom_params_test.py
- tests/data/CustomPrametersTest.glyphs
GSFont with multiple custom parameters with the same name would lose all of them except the last one. It seems some of the code introduced in f7b1e07b63e5a51a59eedbfd31d1df4b8af7f64f handles customParameters as a dictionary, but it is this GlyphsApp hybrid list/dictionary and can have multiple entries with the same name.
This fix restores setting custom parameters using
CustomParametersProxy.__setter__() and introduces the special handling of axes custom parameter to this function.
> Fix multiple custom parameters with the same name on GSFont

- Lib/glyphsLib/builder/constants.py
- Lib/glyphsLib/builder/glyph.py
- Lib/glyphsLib/classes.py
- Lib/glyphsLib/filters/cornerComponents.py
- tests/data/ShapeOrder.glyphs
- tests/glyphs3_test.py
This fixes #895. We do this by:
1) Providing a `.shapes` accessor on the GSLayer object, similar to Glyphs 3 API.
2) Storing a "shapes signature" in the UFO lib for mixed path/component glyphs. For example, if the shape order is "path 1, component 1, path 2, path 3, component 2", a signature will be stored in the layer's lib dictionary with the value `"PCPPC"`. 
3) Using this signature to re-arrange the `.shapes` array when loading UFOs back into Glyphs objects.
4) When processing a corner component, mapping the "shape index" (stored in the hints array) to the "path index" using the signature.
> Store shape indices

- Lib/glyphsLib/builder/anchors.py
- Lib/glyphsLib/builder/constants.py
- Lib/glyphsLib/classes.py
This goes part of the way to fixing #910. It saves any userData on an anchor to the glyph's objectlib dictionary. This allows us to later get at the contextual user data attached to the anchor and generate contextual mark lookups for it.
Ideally we should (a) allow userData on anything which can take a userData on the Glyphs side and serialise it, and (b) convert the UFO objectlibs back to Glyphs objects. But I don't need that today, and I am in a hurry. :-/
> Send anchor userdata to objectlib

- Lib/glyphsLib/classes.py
It is iterating over all masters in the font, then tries to access the master by its id and then checks if the master is None, but this can never happen since we are iterating over already existing masters.
This code is called in a very hot spot, and in a script I’m profiling, it takes more than 50% of the font build time.
Fixes https://github.com/googlefonts/glyphsLib/issues/646
> Remove very slow code that does nothing

- Lib/glyphsLib/builder/layers.py
- Lib/glyphsLib/builder/sources.py
- Lib/glyphsLib/classes.py
- tests/builder/designspace_gen_test.py
In #928 I only fixed the name of the UFO layer containing v3 intermediate (brace) glyphs, but forgot to also set the `layerName` attribute of the corresponding designspace source accordingly. The existing test didn't explicitly check for this, apologies for not detecting this earlier, and thanks @clauseggers for reporting in #925.
I'll first push a (failing) assertion that reproduces the issue then follow up with the actual code fix.
> ensure DS source layer is named correctly for brace glyphs

- Lib/glyphsLib/classes.py
- Lib/glyphsLib/parser.py
- tests/glyphs3_test.py
Remove the file extension check, which should not be our concern, and use `parser.load()` which handles `.glyphspackage` for us.
> Accept `.glyphspackage` in GSFont constructor

- Lib/glyphsLib/builder/constants.py
- Lib/glyphsLib/builder/font.py
- Lib/glyphsLib/featureWriters/markFeatureWriter.py
- tests/data/ContextualAnchors.glyphs
- tests/feature_writers_test.py
See #910. This implements the `*top` (etc.) anchors with an embedded custom context, causing them to replace standard anchor positions in certain contexts. Tested fairly extensively on an internal font project, but:
* No test suite yet
* No mkmk handling yet
> Support contextual anchors

- Lib/glyphsLib/builder/color_layers.py
- tests/builder/builder_test.py
As described in #937, the current color layer implementation writes unicode values for each layer in a color glyph. Recent [fontmake fixes](https://github.com/googlefonts/ufo2ft/pull/739) now treat this as an error which prevents color fonts from building.
This changes `color_layers.py` to set the Unicode mapping on each layer-glyph in the color glyph to an empty list. It does this in `color_layers.py` rather than modifying the `builder.to_ufo_glyph` method because it seems highly specific to color layer-glyphs.
Fixes #937.
> Do not set Unicode values for each layer in a color glyph.

- Lib/glyphsLib/builder/color_layers.py
- tests/builder/builder_test.py
Similar to https://github.com/googlefonts/glyphsLib/pull/939 (color palettes unicodes), this PR ensures that color layers are written without unicodes, which otherwise prevents font generation.
Fixes https://github.com/googlefonts/glyphsLib/issues/946
> Ensure no unicodes for color layers

- .github/workflows/ci.yml
- Lib/glyphsLib/builder/axes.py
- Lib/glyphsLib/builder/custom_params.py
- tests/builder/axes_test.py
- tests/data/IntermediateLayer.glyphs
> Add support for 'Virtual Master' custom parameters

- Lib/glyphsLib/filters/cornerComponents.py
- tests/data/CornerComponents.glyphs
Currently a component like this:
ends up looking like this:
This PR fixes it.
> Correction to corner components

- Lib/glyphsLib/featureWriters/markFeatureWriter.py
- tests/data/IgnorableAnchors.glyphs
- tests/feature_writers_test.py
Glyphs allows anchors to start with non-letter characters and these are used internally to align components and should not be exported to the feature file.
Fixes https://github.com/googlefonts/glyphsLib/issues/963
> markFeatureWriter: Skip ignorable anchors

- Lib/glyphsLib/builder/features.py
In Glyphsapp, users can define names for Stylistic Sets.
Currently, if a user doesn't add a name, GlyphsLib will export the stylistic set with an empty name.
This PR won't add empty names which mimics the behaviour of GlyphsApp's exporter.
I discovered this issue while checking https://github.com/google/fonts/pull/7104. Fontbakery is reporting that the font is missing nameIDs 256, 257 etc which stem from this issue, https://github.com/fonttools/fontbakery/issues/3671#issuecomment-1882830352
> features: Do not include empty labels

- Lib/glyphsLib/featureWriters/markFeatureWriter.py
Follow up from #957 to avoid introducing a too strong dependency on ufo2ft v3.
> make contextual mark writer continue to work with old ufo2ft

- Lib/glyphsLib/builder/__init__.py
- Lib/glyphsLib/builder/builders.py
- Lib/glyphsLib/builder/transformations/__init__.py
- Lib/glyphsLib/builder/transformations/intermediate_layers.py
- Lib/glyphsLib/classes.py
- tests/builder/preflight_test.py
- tests/data/ComponentsWithIntermediates.glyphs
This is kind of the inverse of #954. If an ~alternate~ intermediate layer references a component, and that component does not have a matching intermediate layer, glyphsLib currently generates a "too sparse" master. In the test file in this PR, `Aslash` has an intermediate layer but it uses a component glyph `A` which does not have that intermediate layer. Sometimes the resulting UFO file for the sparse master can't be compiled, because the referenced component `A` is missing; sometimes it can be compiled but there is no variation:
```
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on ComponentsWithIntermediates-Regular-{151}
WARNING:ufo2ft.util:dropping non-existent component 'A' in glyph 'Astroke'
...
WARNING:fontTools.varLib:glyph Astroke has incompatible masters; skipping
``` …
> Build intermediate layers with non-intermediate components

- Lib/glyphsLib/builder/custom_params.py
- Lib/glyphsLib/builder/instances.py
- Lib/glyphsLib/classes.py
- tests/builder/axes_test.py
- tests/classes_test.py
- tests/data/VariableInstance.glyphs
Export Glyphs 3 as DesignSpace v5 variable-fonts, setting their custom parameters is the variable-font lib, mainly using the "public.fontInfo" key.
> Export variable instances as DSv5 variable-fonts

- Lib/glyphsLib/builder/anchor_propagation.py
- tests/data/AnchorPropagation.glyphs
In anchor_propagation.py, we have code (added by @yanone in https://github.com/googlefonts/glyphsLib/pull/617) to adjust propagated anchor position when a mark component is anchored to a specific named anchor as specified in the ComponentInfo lib key (this can be used to specify which of the seveal ligature anchors the given component is supposed to be attached to e.g. top_1, top_2 etc). 
The code indiscriminately applies the adjustment inside a for loop, without checking the anchor names match the expected component anchor.
I modified one of the AnchorPropagation.glyphs test file by changing the order of anchors in a mark glyph used as component in order to trigger a failure (anchor order is itself meaningless, it only happened to work before because the last anchor was the right one).
I …
> [anchor_propagation] fix issue adjusting mark component anchor

- Lib/glyphsLib/cli.py
Fixes https://github.com/googlefonts/glyphsLib/issues/906
Currently glyhps2ufo does the anchor propagation by default, unless the .glyphs file contains "Propagate Anchors" custom parameter set to false. There is a `--propagate-anchors` option but it doesn't do much since we do it even when the custom parameter is missing.
This PR adds the mutually exclusive `--no-propagate-anchors` which will disable this without having to modify the .glyphs file to add the custom parameter.
> [glyphs2ufo] add --no-propagate-anchors CLI option

- Lib/glyphsLib/builder/instances.py
- tests/builder/axes_test.py
- tests/data/VariableInstance.glyphs
Fixes https://github.com/googlefonts/glyphsLib/issues/981
> compose DSv5 variable-font filename like Glyphs.app would name exported VFs

- Lib/glyphsLib/classes.py
this `if` branch was never true because of a typo (the author probably meant to compare axis.minimum with 'axis_min'  instead of 'axis_max'); but besides that, even if we did fix the typo, it would be incorrect to ignore such an explict always-true axis rule where both min and max are explicitly declared and are equal to the axis min/max. Glyphs.app exports a GSUB with a FeatureVariation table with an empty condition set (which means always apply), and fontmake does the same.
The PR doesn't change anything, only removes code that's never evaluated so no functional change.
> remove spurious continue in _bracket_info()

- tests/builder/builder_test.py
and
DeprecationWarning: The beginPath method needs an identifier kwarg.
> Fix "UserWarning: The pointPen needs an identifier kwarg."

- Lib/glyphsLib/builder/glyph.py
- tests/builder/builder_test.py
If a glyph name ends with ".uvNNN" with NNN ranging from 001 to 256, then it is a variation sequence with uv001 being U+0xFE00 and uv256 being U+0xE01EF.
The only documentation for this is the "More Improvements" section in Glyphs 2.6.1 announcement:
https://glyphsapp.com/news/glyphs-2-6-1-released
And this forum post:
https://forum.glyphsapp.com/t/unicode-variation-selector-u-fe00/21701
Fixes https://github.com/googlefonts/glyphsLib/issues/681
> Handle Unicode Variation Sequences

- tests/glyphdata_test.py
This function has very particular behaviour that was not covered by existing tests. (I'm porting this to Rust, and found this logic tricky; might as well backport the test cases)
> [glyphdata] Add test to hit _split_glyph_name

- Lib/glyphsLib/featureWriters/markFeatureWriter.py
- tests/data/ContextualAnchors.glyphs
- tests/feature_writers_test.py
Instead of making one `pos` statement per individual base glyph (which translates to one subtable, at least in feaLib), group all base glyphs in one statement. When there is a large number of base glyphs with the same contextual anchor, this can save quite a bit (for a font I’m working on, this save ~4kb for an anchor with 93 base glyphs).
> markFeatureWriter: Optimize contextual anchor lookups

- Lib/glyphsLib/classes.py
- tests/classes_test.py
> GSLayer: fix name property when parent GSGlyph is in turn orphan

- Lib/glyphsLib/builder/__init__.py
- Lib/glyphsLib/builder/anchor_propagation.py
- Lib/glyphsLib/builder/builders.py
- Lib/glyphsLib/builder/transformations/__init__.py
- Lib/glyphsLib/builder/transformations/propagate_anchors.py
- Lib/glyphsLib/util.py
- tests/builder/builder_test.py
- tests/builder/designspace_gen_test.py
- tests/builder/transformations/propagate_anchors_test.py
- tests/classes_test.py
- tests/data/PropagateAnchorsTest-propagated.glyphs
- tests/data/PropagateAnchorsTest.glyphs
Fixes https://github.com/googlefonts/glyphsLib/issues/368
This PR translates the fontc' [`propagate_anchors.rs`](https://github.com/googlefonts/fontc/blob/main/glyphs-reader/src/propagate_anchors.rs) from Rust to Python and applies the transformation to the GSFont in the 'preflight' step before it gets passed on to the UFOBuilder.
The Rust code was based off the original Glyphs.app's Objective-C code (Georg shared a snippet with us privately) and is as such more 'correct' then the old, reverse-engineered implementation.
The previous `glyphsLib.builder.anchor_propagation` module is now deprecated but is kept around in case users may instantiate the UFOBuilder class directly with propagate_anchors=True.
Also, the existing `propagate_anchors` parameters of `to_designspace`, `to_ufos` and …
> Port fontc' propagate_anchors.rs to .py; apply it as preflight transformation

- Lib/glyphsLib/builder/__init__.py
- Lib/glyphsLib/builder/builders.py
- tests/builder/builder_test.py
> Fix AttributeError when parsing optional glyph_data parameter

- Lib/glyphsLib/builder/transformations/propagate_anchors.py
- tests/builder/transformations/propagate_anchors_test.py
Fixes #1022 
cyclical composites with infinite component depth are now correctly detected and skipped with a warning (they will probably just error out down the pipeline anyway).
~~We traverse the component trees in depth-first order while keeping track of the glyphs that we are currently visiting so we can detect cycles as they happen.~~
EDIT: I now copied @cmyr's solution from https://github.com/googlefonts/fontc/pull/907
We now keep track of the composites that are waiting for their components as we process the queue, as well as the length of the queue at that point, and if we encounter the same glyph twice without the queue having gotten smaller it means we aren't making any more progress, thus we have a cycle.
Also, since we currently can only resolve component refs between master …
> [propagate_anchors] detect component cycles, fix infinite loop

- Lib/glyphsLib/builder/features.py
- tests/builder/features_test.py
Partially addresses #761, #763, and #1026 by handling the `minimal=True` case only.
> Drop disabled prefixes, classes, and features in minimal mode

- Lib/glyphsLib/builder/constants.py
We want curs feature lookups to come first, then kerning, then mark/mkmk, but we currently are calling CursFeatureWriter last which causes its lookups to be also written last. The lookup order does not matter for HarfBuzz, but it matters for other implementations, see: https://github.com/harfbuzz/harfbuzz/issues/4596#issuecomment-2220558649
> Fix the order of feature writers

- Lib/glyphsLib/__init__.py
- Lib/glyphsLib/classes.py
This helps avoid a costly and redundant save-and-load for Glyphs sources that are manipulated in memory prior to conversion.
> Allow GSFont object to be passed to `build_masters` directly (in place of a path)

- Lib/glyphsLib/builder/names.py
- Lib/glyphsLib/classes.py
- tests/classes_test.py
This is a rebase of #999 after I accidentally broke it.
>  Support fonts named Oblique instead of Italic

- Lib/glyphsLib/builder/custom_params.py
- Lib/glyphsLib/classes.py
- tests/builder/custom_params_test.py
Fixes https://github.com/googlefonts/glyphsLib/issues/905
> skip disabled custom parameters when glyphs=>ufo and minimal=True

- Lib/glyphsLib/builder/transformations/propagate_anchors.py
- Lib/glyphsLib/classes.py
- tests/builder/transformations/propagate_anchors_test.py
- ~~Don’t propagate contextual anchors, GlyphsApp does not propagate them.~~ It actually does, so this part is later reverted.
- When copying anchors, copy also userData, otherwise the context of contextual anchors of any processed glyph will be dropped. This is a regression from https://github.com/googlefonts/glyphsLib/pull/1011
> propagate_anchors: fix handling of contextual anchors

- Lib/glyphsLib/builder/kerning.py
Fixes #1039
```diff
--- master_ufo/PlaypenSans-Regular.ufo/kerning.plist	2024-10-31 10:32:42
+++ master_ufo_2/PlaypenSans-Regular.ufo/kerning.plist	2024-10-31 10:32:52
@@ -14,7 +14,11 @@
</dict>
<key>public.kern1.quotesingle</key>
<dict>
+      <key>public.kern2.A</key>
+      <integer>-49</integer>
<key>public.kern2.bet-hb</key>
+      <integer>-20</integer>
+      <key>public.kern2.space</key>
<integer>-20</integer>
</dict>
<key>public.kern1.space</key>
```
> Don't unnecessarily drop LTR kerns when combining with RTL

- Lib/glyphsLib/builder/custom_params.py
- tests/builder/builder_test.py
Unless "Keep GlyphOrder" (or the older "TrueType Keep GlyphOrder") custom parameter is set to True.
> [builder] Reorder .notdef and space glyphs in public.glyphOrder

- Lib/glyphsLib/builder/paths.py
- tests/builder/lib_and_user_data_test.py
Roundtrip point identifiers from GSNode.userData["UFO.identifier"] to UFO Point.identifier and back, as described in #1049.
Same as #1054, but for the Glyphs3-merge branch.
> Handle point identifiers (Glyphs 3)

- Lib/glyphsLib/filters/eraseOpenCorners.py
- tests/eraseOpenCorners_test.py
Specifically if a curve contains only two segments, we should not ever be erasing a corner.
A curve like this exists in the `K.ss02` glyph of [Estonia Pro](https://github.com/googlefonts/estonia).
> Fix edge case in open corner erasure logic

- Lib/glyphsLib/filters/eraseOpenCorners.py
- tests/eraseOpenCorners_test.py
In the process of porting this functionality to Rust, I've run into a funny issue: in some cases, after erasing corners, the outline generated here contained an extra duplicate point at the beginning.
This error seems to be introduced only for contours where the last segment is a curve, and it is introduced early; even before we start processing, there is an extra segment in the segments list for these contours.
This patch addresses this by changing the logic of closePath to not emit a final line segment if it would be a duplicate, but I'm not totally confident that this is the right approach.
---
More detail: I believe that what is going on is an interaction between the logic for `closePath` in `eraseOpenContours` and the logic in the `PointToSegmentPen` that is [writing into …
> Fix extra segment in eraseOpenCorners

- Lib/glyphsLib/builder/glyph.py
- tests/builder/builder_test.py
A nice win for crater.
- fixes #1059
> Consider unicodes when zeroing mark glyph widths

- Lib/glyphsLib/builder/custom_params.py
- Lib/glyphsLib/classes.py
- tests/builder/custom_params_test.py
Currently the problem is occurring in the parser. #807
```
File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 81, in _parse_dict
self._parse_dict_into_object(res, text)
File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 98, in _parse_dict_into_object
res[name] = d[name]
File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/classes.py", line 336, in setitem
setattr(self, key, value)
File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/classes.py", line 1366, in setValue
value = readIntlist(value)
File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/types.py", line 349, in readIntlist
return _mutate_list(int, src)
File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/types.py", line 344, in …
```
> Support new codepage ranges syntax #530

- tox.ini
Python 3.8 is passed end-of-life.
See https://devguide.python.org/versions/
> tox: Use py3.9 and up

- Lib/glyphsLib/glyphdata.py
- tests/glyphdata_test.py
E.g. a ligature glyph named "one_one-han.paren" (as found in ButTaiwan/iansui) gets renamed "one_one.paren" in Glyphs.app whereas in glyphsLib it was keeping the original name including the script suffix (stripped of hyphen) but the script itself is not used by any of the ligature components.
> glyphdata: strip unused script -suffix from ligature production name

- Lib/glyphsLib/builder/instances.py
- tests/builder/interpolation_test.py
This seems to be the new property specifically for fvar instance postscript name, so try it first:
https://handbook.glyphsapp.com/custom-parameter-descriptions/#custom-parameter/variablePostscriptFontName https://github.com/googlefonts/fontc/pull/1525
> [builder] Use variablePostscriptFontName from instances if present

- Lib/glyphsLib/builder/axes.py
- Lib/glyphsLib/builder/instances.py
- Lib/glyphsLib/classes.py
- tests/builder/designspace_gen_test.py
- tests/classes_test.py
- tests/data/GlyphsUnitTestSans.glyphs
This matches Glyphs.app's behavior.
Fixes https://github.com/googlefonts/glyphsLib/issues/905
> treat disabled custom parameters as missing when getting them by name

- Lib/glyphsLib/builder/transformations/align_alternate_layers.py
I noticed what looks like a regression with glyphsLib v6.11.2, specifically after https://github.com/googlefonts/glyphsLib/pull/1092 got merged
the previous `find_component_use` code in `bracket_layers.py` was considering alternate layers inside glyphs marked as non-exportable whereas in the new align_alternate_layers.py that replaced it, I thought I might skip those but turns out it's possible for composite glyphs to reference component glyphs that are in turn marked as export=False and the code still needs to be able to align alternate layers definitions across these. At least that's my current understanding..
This is reproducible with the following ttx_diff.py command
```
python3 resources/scripts/ttx_diff.py 'https://github.com/googlefonts/Playfair?a49f9f9dc9#sources/Playfair.glyphspac …
```
> [align_alternate_layers] must not skip non-export glyphs when collecting alternate layers
